### ISSUE TITLE
Workaround for fetchDependencies exit trap shell causing issues for callers

### ISSUE THREAD

**Issue by ubitux** [KhronosGroup/MoltenVK#1002]
`fetchDependencies` has a trap on `EXIT` which makes it hardly usable in a `Makefile`.

Here is a typical use case:

`runme.sh`:
```sh
#!/bin/sh
trap "kill 0" EXIT
```

`Makefile`:
```make
all:
	./runme.sh
```

```console
% make
./runme.sh
zsh: terminated  make
% echo $?
143
```

Workaround: `./fetchDependencies --no-parallel-build`

**Comment by billhollings** [comment]
Thanks for providing the workaround.

**Comment by js6i** [comment]
Is this about killing stray child processes? Maybe it could use something like `kill $(jobs -p)` for that, or make itself a group leader and target the group.

**Comment by billhollings** [comment]
>Is this about killing stray child processes?

No, I don't think so.

`fetchDependencies` has a parallelization option (on by default) to build the dependency libraries for multiple platforms in parallel by spawning multiple `xcodebuild` processes and then waiting for them to finish.

The `--no-parallel-build` builds each platform in series and does not spawn and wait for any other processes.

I'm happy to hear ideas for how to run the parallelization spawning without trapping.

Also...the multi-build parallelization effort doesn't actually save that much time (maybe 10%-ish?), because Xcode already does a pretty good job of parallelizing each individual platform to maximize CPU usage efficiency. So...if this parallel spawning design within `fetchDependencies` is causing problems, we can just remove it altogether.

**Comment by js6i** [comment]
My point was, is the point of this trap to kill the script's children if it exits prematurely? If so, I think it could trap this `kill $(jobs -p)` command instead of `kill 0`. Or else, set up it's own process group and then `kill 0` would not kill the calling process that does not isolate children in their own group (like make, apparently).
Otherwise, what is the point of it?

**Comment by billhollings** [comment]
PR #1066 makes `--no-parallel-build` the default option. 

Building in parallel does not significantly improve performance, and as shown here, makes it
more difficult to integrate calling fetchDependencies from a larger build script,
because of the need to trap and kill child processes on an error.
