### ISSUE TITLE
Generate to a wrong MSL from SPIRV

### ISSUE THREAD

**Issue by daemyung** [KhronosGroup/MoltenVK#1027]
This issue is that SPIRV-Cross generates wrong MSL. The error message is below
```
validateFunctionArguments:3476: failed assertion `Fragment Function(main0): missing buffer binding at index 2 for headIndexImage_atomic[0].'
```
However a resource at index 2 is not buffer. It's image. Below is shader's resources.
```
layout (set = 0, binding = 1) buffer GeometrySBO
{
    uint count;
    uint maxNodeCount;
};

layout (set = 0, binding = 2, r32ui) uniform uimage2D headIndexImage;

layout (set = 0, binding = 3) buffer LinkedListSBO
{
    Node nodes[];
};
```
You can find this shader at Vulkan/data/shaders/glsl/oit

You can reproduce this issue very easily. Follow below steps to reproduce this issue.
1. git clone --recursive https://github.com/SaschaWillems/Vulkan.git
2. python download_assets.py
3. Generate a project using cmake.
```
mkdir build
cd build
cmake -G "Xcode .."
```
4. Build `oit` example  and run.

My VulkanSDK is 1.2.148.
```
Revisions used to build this SDK on Tue Aug 11 20:08:23 2020
fc87182aab33a63b43db41d7a424eed27283aebf : https://github.com/KhronosGroup/Vulkan-Headers.git
2ad4e990f5a47d3556a5912acfa9fc7dc475fc0e : https://github.com/KhronosGroup/Vulkan-Loader.git
91cb71f2fa0c4d710cf188e89b4f7d1a2a0e5879 : https://github.com/KhronosGroup/Vulkan-ValidationLayers.git
3f7ccf2cce264525d14361ac563e7a6ba9a54f54 : https://github.com/KhronosGroup/Vulkan-Tools.git
3ce31c1c29919f0695d2d4d4990f29a90e39bcf6 : https://github.com/LunarG/VulkanTools.git
8f6edef8ba54503f70064ea94b0fb0020dcca819 : https://www.github.com/KhronosGroup/MoltenVK.git
3ee5f2f1d3316e228916788b300d786bb574d337 : https://github.com/KhronosGroup/Glslang.git
895927bd3f2d653f40cebab55aa6c7eabde30a86 : https://github.com/KhronosGroup/SPIRV-Tools
979924c8bc839e4cb1b69d03d48398551f369ce7 : https://github.com/KhronosGroup/SPIRV-Headers
0376576d2dc0721edfb2c5a0257fdc275f6f39dc : https://github.com/KhronosGroup/SPIRV-Cross.git
ce6d5fea448e3a077f8d64e0352ec3d5f38b3dcc : https://github.com/google/shaderc.git
```

I suspect this issue is SPIRV-Cross however I don't check what is exactly happend in MoltenVK. So I have raised up issue at here first.

**Comment by cdavis5e** [comment]
What's going on here is that we're adding a buffer corresponding to the image `headIndexImage` to the shader, which we use for atomics on that image. This is because Metal does not yet support atomics directly on textures.

The problem comes when you use an image with optimal tiling here. There is no buffer backing it; therefore, there is no buffer to give to the shader.

Does the shader in question use image atomics? If not, then we'll probably need to have SPIRV-Cross not emit the extra buffer in that case. But if so, then there's nothing we can do until textures in Metal support atomic ops.

Also, note that the SPIR-V bindings do not necessarily correspond to the bindings in the generated MSL. This is because Metal has separate binding spaces for buffers, textures and samplers.

**Comment by cdavis5e** [comment]
> Does the shader in question use image atomics?

Based on the link you gave, it does not. So we'll need to not emit the extra buffer in this case.

**Comment by cdavis5e** [comment]
> > Does the shader in question use image atomics?
> 
> Based on the link you gave, it does not. So we'll need to not emit the extra buffer in this case.

Oh wait, there's a second one that *does* use atomics. Also, SPIRV-Cross already doesn't emit that buffer if no atomic ops are used in the shader.  So there's nothing we can do right now.

**Comment by daemyung** [comment]
@cdavis5e Let's summerize.
1. Image atomic operation is not supported on Metal. Right?
2. If the image tiling is LINEAR then MoltenVK creates a buffer inside VkImage and binds a buffer to the argument table internally? However after I have changed to create image, I have faced the same issue.
```
validateFunctionArguments:3476: failed assertion `Fragment Function(main0): missing buffer binding at index 2 for headIndexImage_atomic[0].'
```

Below code is how I create an image.
```
VkImageCreateInfo imageInfo = vks::initializers::imageCreateInfo();
imageInfo.imageType = VK_IMAGE_TYPE_2D;
imageInfo.format = VK_FORMAT_R32_UINT;
imageInfo.extent.width = width;
imageInfo.extent.height = height;
imageInfo.extent.depth = 1;
imageInfo.mipLevels = 1;
imageInfo.arrayLayers = 1;
imageInfo.samples = VK_SAMPLE_COUNT_1_BIT;
imageInfo.tiling = VK_IMAGE_TILING_LINEAR;
imageInfo.usage = VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_STORAGE_BIT;

VK_CHECK_RESULT(vkCreateImage(device, &imageInfo, nullptr, &geometryPass.headIndex.image));

geometryPass.headIndex.imageLayout = VK_IMAGE_LAYOUT_GENERAL;

VkMemoryRequirements memReqs;
vkGetImageMemoryRequirements(device, geometryPass.headIndex.image, &memReqs);

VkMemoryAllocateInfo memAlloc = vks::initializers::memoryAllocateInfo();
memAlloc.allocationSize = memReqs.size;
memAlloc.memoryTypeIndex = vulkanDevice->getMemoryType(memReqs.memoryTypeBits, VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
```

**Comment by cdavis5e** [comment]
> 1. Image atomic operation is not supported on Metal. Right?

That's correct.

> 2. If the image tiling is LINEAR then MoltenVK creates a buffer inside VkImage and binds a buffer to the argument table internally?

Usually.

> However after I have changed to create image, I have faced the same issue.

Sometimes, though, it won't create a buffer underlying it, even if you ask for `LINEAR` tiling. Using host-coherent memory on Mac is one of those times. This is because MoltenVK creates `MTLBuffer`s for `VkDeviceMemory` objects, not for individual resources. So the buffer will have storage type `MTLStorageModeShared`, which, prior to macOS 10.15.5, cannot be used to create a texture. I have a patch to let MoltenVK create `Shared` linear textures and texture buffers, but I'm still testing it to make sure I didn't break anything (that wasn't already broken).

I think I've figured out a way to make this always work, even for `OPTIMAL`-tiled images. Stand by; I'm testing *that* patch, too...

**Comment by daemyung** [comment]
Ok I will check soon.

**Comment by daemyung** [comment]
Do you know when it will release in VulkanSDK?
