### ISSUE TITLE
Feature request: VK_EXT_debug_marker for GPU frame capture

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/MoltenVK#11]
It would be very useful if MoltenVK could support VK_EXT_debug_marker and pass the markers down to Metal so that they showed up during GPU Frame Capture.  For example, in Source 2 we label all command buffers and many resources and seeing that within the Metal GPU Frame Capture would be very helpful.

**Comment by billhollings** [comment]
PR #588 adds support for `VK_EXT_debug_report`, which is the prerequisite for `VK_EXT_debug_marker`.

**Comment by billhollings** [comment]
PR #608 implements this extension.

One implementation limitation is the labelling of pipelines. Unfortunately, for some strange reason, the labels of Metal pipelines are readonly, and Metal only allows the label of a pipeline to be set during pipeline creation, via the pipeline descriptor. 

I explored potentially delaying the creation of the Metal pipeline to give the app a chance to set the pipeline object name, but we really need to go all the way and create the Metal pipeline during Vulkan pipeline creation in order to provide error feedback to the app. 

In the end…I opted to name the pipeline after the name of the pipeline layout.

There is the option of recompiling the Metal pipeline whenever a name is set for the corresponding Vulkan pipeline. But I didn’t want to assume an app would be happy with that behaviour, since it would obviously double pipeline creation time for any app that innocently sets a debug name for its pipelines. 

But I am happy to hear feedback on that option.
