### ISSUE TITLE
Static linking not supported anymore?

### ISSUE THREAD

**Issue by repi** [KhronosGroup/MoltenVK#1122]
We've ([Embark](https://embark.games)) been maintaining in our [`ash-molten`](https://github.com/EmbarkStudios/ash-molten) crate Rust bindings in with MoltenVK with the specific purpose of building and statically linking in MoltenVK to Rust applications, but noticed that in the new v1.1.0 release classic static linking support has been removed and only dynamic linking is supported anymore?

We ran into this when trying to upgrade to v1.1.0, https://github.com/EmbarkStudios/ash-molten/pull/25

Is there any way to still do static linking, is the XCFramework path intended to replace it? (I'm not too familiar with the Mac build specifics).

**Comment by billhollings** [comment]
Static libraries and frameworks are definitely still supported.

For static linking, Apple's evolution of frameworks is to move to the newer `XCFramework` constructs. While older static and framework linking is still supported, the move became more of a priority with the recent introduction of Apple Silicon (`arm64`) for macOS, as it changes the nature of fat libraries because `arm64` must now be a component of Simulator and Mac Catalyst builds (starting with Xcode 12.2). Because of this, multi-platform fat libraries are no longer feasible, since a fat library cannot contain two `arm64` architecture builds that are destined for different platforms.

`XCFrameworks` can be linked similarly to the old-style frameworks. The `MoltenVK_Runtime_UserGuide.md` document includes instructions for using them to link your app to MoltenVK.

If your build process really, really needs to link directly to a `libMoltenVK.a` file instead of a framework, you can find them inside `MoltenVK.xcframework` (which is mostly just a use-specific directory), filed under their architectures (eg- `macos-x86_64/libMoltenVK.a`). I guess we should add this last point to the `MoltenVK_Runtime_UserGuide.md` document.

**Comment by repi** [comment]
Great to hear, and thanks for answering and confirming. Will experiment with the XCFramework and see if get it to work
