### ISSUE TITLE
FindVulkan.cmake for macOS

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/MoltenVK#116]
It would be useful for cross-platform Vulkan projects using cmake for Windows/Linux if there was also support for FindVulkan.cmake on macOS using the LunarG SDK/MoltenVK.  T

**Comment by oscarbg** [comment]
+1

**Comment by karl-lunarg** [comment]
Here's a minimal CMake file that builds the `vulkaninfo` console (Terminal) client and uses the existing `FindVulkan.cmake` module:

CMakeLists.txt:
```cmake
cmake_minimum_required(VERSION 3.10)
project(vulkaninfo)
find_package(vulkan REQUIRED)
add_executable(vulkaninfo vulkaninfo.c)
target_link_libraries(vulkaninfo Vulkan::Vulkan)
```

Environment Variables:

```shell
VK_ICD_FILENAMES=/Users/karl/Desktop/vulkansdk-macos-1.0.69.0/macOS/etc/vulkan/icd.d/MoltenVK_icd.json

VULKAN_SDK=/Users/karl/Desktop/vulkansdk-macos-1.0.69.0/macOS/
```

Put the above CMakeLists.txt file in an empty directory someplace.

Then get a copy of the `vulkaninfo.c` file.  Be aware that you can't use the latest from the Vulkan-LoaderAndValidationLayers repo because it has been ported to Vulkan 1.1 and you need a 1.0 version for this macOS SDK.  This [version](https://raw.githubusercontent.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/sdk-1.0.68/demos/vulkaninfo.c) will work.
Put the `vulkaninfo.c` file in the same directory as `CMakeLists.txt`.

Set the specified environment variables, adjusting for the actual location of your SDK.

Then:

```shell
mkdir build
cd build
cmake ..
make
./vulkaninfo
```

and you should see the output of vulkaninfo in your terminal.

Is the above sufficient to address this issue?  It illustrates how to locate the Vulkan loader and header files in the SDK from a CMake project.

Edit: projects -> project in CMake file.

**Comment by danginsburg** [comment]
> Is the above sufficient to address this issue? It illustrates how to locate the Vulkan loader and header files in the SDK from a CMake project.

Yes, this is perfect, thanks!

**Comment by karl-lunarg** [comment]
I've added this information to the SDK's Getting Started guide.

@billhollings I think you can close this issue now.

**Comment by billhollings** [comment]
@karl-lunarg Thanks!
