### ISSUE TITLE
Cannot compile MoltenVK-macOS on macOS 15.7

### ISSUE THREAD

**Issue by SachiSakurane** [KhronosGroup/MoltenVK#1197]
I was building according to the Readme.md, but I encountered the following error in `MoltenVKPackaging.xcodeproj`.

```
/MoltenVK/MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.mm:213:107: 'MTLStorageModeMemoryless' is unavailable: not available on macOS
```

I checked `MTLStorageModeMemoryless`, and it is only available on macOS 11.0+.
https://developer.apple.com/documentation/metal/mtlstoragemode/mtlstoragemodememoryless

**Comment by cdavis5e** [comment]
Normally, MoltenVK requires the SDKs from the latest released version of Xcode. However, because the release of macOS 11 was delayed, we made an exception and supported building with Xcode 11.x. At some point, we're probably going to remove those guards we added, and you'll need Xcode 12 to build.

For now, though, #1198 should fix your build problem.

**Comment by cdavis5e** [comment]
CI has mostly passed, so I'm 99% certain this will fix your build problem. (I wonder if we should add a CI instance for building with Xcode 11 on Catalina...)

**Comment by SachiSakurane** [comment]
I tried #1198 locally, and it passed! Thank you for resolving so quickly.
