### ISSUE TITLE
Apple M1 is advertised as a discreted device

### ISSUE THREAD

**Issue by nihui** [KhronosGroup/MoltenVK#1201]
AFAIK, Apple M1 is the integrated one. It does not have device local memory.

**Comment by cdavis5e** [comment]
This is technically true. However, the M1's `MTLDevice` returns `NO` for `lowPower`. Apple explained that this is because its performance characteristics are those of a discrete, high-performance GPU (i.e. one made by NV or AMD), not an integrated GPU (e.g. one made by Intel). MoltenVK sets the GPU type based on this property. I'm not sure we should add a special case for Apple GPUs to make them `INTEGRATED` instead of `DISCRETE`.

**Comment by billhollings** [comment]
> memory access characteristics are those of an integrated GPU

This is probably what matters in terms of "integrated" vs "discrete".

I think I used `lowPower` as a shortcut way of detecting which of the two GPU's on a typical Mac was the integrated one. But maybe we do need to be more subtle in detecting this now.
