### ISSUE TITLE
Add support for extension VK_KHR_shader_non_semantic_info_extension

### ISSUE THREAD

**Issue by richard-lunarg** [KhronosGroup/MoltenVK#1214]
Can you add support for the VK_KHR_shader_non_semantic_info extension? This will also require support for the SPV_KHR_non_semantic_info extension as well. The shader based debug printf validation tests requires these extensions, and technically without them the behavior of debug printf is undefined.

**Comment by richard-lunarg** [comment]
Actually the GPU validation and DebugPrintf validation features need two extensions: VK_KHR_shader_non_semantic_info and VK_EXT_multi_draw.

**Comment by Hugobros3** [comment]
@richard-lunarg could this requirement be eased when only printf validations is used ? especially for compute stages, I don't understand why multi_draw would play a role.

I believe enabling the VK_KHR_shader_non_semantic_info is a matter of just exposing it - maybe stripping those instructions in SPIRV-Cross too, if it can't do it already.

**Comment by billhollings** [comment]
What are we looking for in implementing these extensions? Is the absence causing problems? If so, what problems? And do we need specific functionality?

- `VK_KHR_shader_non_semantic_info` (functional) - Metal doesn't natively support debug printing from a shader. We could likely implement the functionality by writing to a buffer within the shader, and have the CPU extract the message content from the buffer after the command buffer completes, and then send it to a debug report (and `stderr` log). This would be a significant and complicated workaround effort, so we'd need to make sure it made sense to commit to it.

- `VK_KHR_shader_non_semantic_info` (non-functional) - Alternately, we could implement the extension just to have it exist, but subsequently ignore any shader debug printing. This would be a fairly simple implementation.

- `VK_EXT_multi_draw` - I'd like to understand what this extension has to do with debug printf? Implementing this extension shouldn't be a problem, at least functionally, although we probably wouldn't achieve the stated goal of the `VK_EXT_multi_draw` extension, to improve state-management and performance over the equivalent serial draw commands.

**Comment by Hugobros3** [comment]
To the best of my understanding, the validation layers instrument shaders by intercepting SPIR-V at module creation time (so the fact it goes through SPIRV-Cross later is irrelevant) and adding a descriptor set for binding the buffers etc. As well as the host code for printing. So the driver doesn't need to do anything beside support the required extensions, hence @richard-lunarg's request

Debug print is extraordinarily useful, especially in the absence of proper GPU debuggers, lacking it on MVK is a big drag IMO.

As for multi-draw requirement, I'm not sure, it might have to do with some technicalities for writing to the buffer during the vertex stages or something. I can't see it being needed in compute stages

**Comment by billhollings** [comment]
> Debug print is extraordinarily useful, especially in the absence of proper GPU debuggers, lacking it on MVK is a big drag IMO.

Thanks for the feedback. Very helpful.

**Comment by billhollings** [comment]
Slang has a shader-based [GPU printing](https://github.com/shader-slang/slang/tree/master/examples/gpu-printing) mechanism that we might be able to investigate and take ideas from.

**Comment by Hugobros3** [comment]
again, the instrumentation in the validation layer implements this by instrumenting the shader. vulkan drivers do not implement it. i got this working on my own machine simply by patching moltenvk to expose support for the required extensions (no extra functionality is actually required here!)

**Comment by spnda** [comment]
First of all, since the `VK_KHR_shader_non_semantic_info` extension is already marked as supported, this issue could be closed already.

> Slang has a shader-based [GPU printing](https://github.com/shader-slang/slang/tree/master/examples/gpu-printing) mechanism that we might be able to investigate and take ideas from.

@billhollings About the debug printf, as @Hugobros3 already pointed out, MoltenVK has to do nothing to support that itself. Slang has an example how one could do it manually, but the debug printf extension from the validation layers (which is what everyone would use) essentially does exactly what the Slang example does, and automatically changes shaders and adds the required descriptors to store printed strings.

> Actually the GPU validation and DebugPrintf validation features need two extensions: VK_KHR_shader_non_semantic_info and VK_EXT_multi_draw.

@richard-lunarg I can't find where the VVL's debug printf implementation requires the `EXT_multi_draw` extension. In [debug_printf.cpp](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/layers/gpu_validation/debug_printf.cpp) there is no reference to either of the extensions you mentioned.

**Comment by billhollings** [comment]
@Hugobros3 @spnda  Thanks for reminding me again about the VVL support for debug print. If that is sufficient, then our work here is done.

As @spnda mentions, I actually added `VK_KHR_shader_non_semantic_info` shortly after this issue was posted. I left this issue open because of the outstanding questions about `VK_EXT_multi_draw`, but I should have documented the  `VK_KHR_shader_non_semantic_info` completion here at least.

I'm going to mark this issue as completed, to avoid future confusion on this (mostly mine, apparently).

@richard-lunarg If there is a need for `VK_EXT_multi_draw`, can you open a separate issue for that, please?
