### ISSUE TITLE
Avoid to rely on .git at build time

### ISSUE THREAD

**Issue by SpaceIm** [KhronosGroup/MoltenVK#1277]
It would be nice if MoltenVK could avoid to depend on the .git folder at build time.

Currently, it's required due to `gen_moltenvk_rev_hdr.sh` script which generates a mandatory header file for `MVKDevice.mm`, based on commit hash pointed by HEAD.

It's not very convenient for users or package managers who download archives releases and do not expect to git clone a project to build it.

**Comment by billhollings** [comment]
Thanks. This is a good point.

We'll figure out a better entry point for that script, so it generates the file when associated with Git, but not have it needed at build time.

**Comment by billhollings** [comment]
Can  you clarify what the problem is that you are encountering with the current design?

In our testing, if the Git repo (`.git`) is not present, or even if `git` is not present on the build machine, the `mvkGitRevDerived.h` is still created, is loaded during a build, and the MoltenVK build is successful. 

At runtime, the result is an empty string in the `mvkRevString` var within that file, which drives a different value for `pipelineCacheUUID` for instances for that build than if Git was available, but it is consistent for all uses of that build, and does not interfere with runtime operation.

Where is this going wrong for you? And what do you need it to do to avoid that?

**Comment by SpaceIm** [comment]
My bad. You're right, it works even without `.git` folder or `git` on build machine.
When I opened this PR, I was also not sure of the consequences of an empty `mvkRevString`, but it seems harmless. Thanks for this explanation.

I close this issue.
