### ISSUE TITLE
Crash in MVKDeviceMemory destructor

### ISSUE THREAD

**Issue by TheMrButcher** [KhronosGroup/MoltenVK#1315]
I have VkDeviceMemory and single VkBuffer bound to it. I always call vkDestroyBuffer before vkFreeMemory. But sometimes
I get crash with the next stack:
```
0  _ZN9MVKBuffer16bindDeviceMemoryEP15MVKDeviceMemoryy + 4422726832
1  _ZN15MVKDeviceMemoryD2Ev + 4422832724
2  _ZN15MVKDeviceMemoryD0Ev + 4422833728
3  vkFreeMemory + 4423118320
```

So some MVKBuffer is still bound to MVKDeviceMemory. It can be only one buffer which I already tried to destroy using vkDestroyBuffer. But it wasn't destroyed because it is retained by MVKBufferDescriptor. I don't delete descriptor sets, instead I put them in cache for later use. So they can retain some objects like this MVKBuffer. And if I simultaneously call vkFreeMemory on Thread1 and update descriptor set which previously hold reference to the MVKBuffer bound to the VkDeviceMemory on Thread2, I get this crash (there is no lock guard in MVKDeviceMemory destructor or any other protection, so it can call bindDeviceMemory of already destroyed MVKBuffer). IMHO all of these actions are legal according to Vulkan spec. But it crashes on MoltenVK. And it doesn't crash on any Android device running my app.

**Comment by billhollings** [comment]
Between `MVKBuffer` and `MVKDeviceMemory`, whoever dies first should break the connection between the two objects. 

Are you seeing this _**only**_ during multithreaded race-conditions when `vkFreeMemory()` is called at the same time as the descriptor set is replacing the expired `MVKBuffer` on another thread? Or is it occurring naturally under single thread conditions as well?

**Comment by TheMrButcher** [comment]
Yes, they should break connection, but if they do it simultaneously, crash happens.

I didn't check if it can happen in single-threaded app, but I don't see any way how it can be broken under single thread conditions (every element of buffCopies in ~MVKDeviceMemory must be alive, it can't be destroyed simultaneously). My app is multi-threaded.

**Comment by billhollings** [comment]
@cdavis5e 

I'm mulling over how to fix this web of connections.

The retention of resources in descriptors [originated here](https://github.com/KhronosGroup/MoltenVK/pull/329), for good reason, because Vulkan explicitly requires that descriptors can hold and submit destroyed resources.

In looking at the connections between `MVKBuffer/MVKImage` and `MVKDeviceMemory`, the connections go both ways, so adding locks on the `MVKDeviceMemory` destructor as suggested above will likely result in having to work around reentrant paths.

Plus if that was solved, it leaves the buffer/image held in a descriptor without a device memory, which we'd have to work around to avoid crashing if the descriptor is used.

I'm left wondering if the solution is simply to retain the device memory in `MVKResource`, and release it on unbinding and resource destruction. So, a destroyed but retained buffer in a descriptor would also retain the device memory after it was destroyed. Once the descriptor lets go of the buffer, it would cascade to release the buffer and the device memory.

Some relevant spec talk:

>Before freeing a memory object, an application must ensure the memory object is no longer in use by the device—​for example by command buffers in the pending state. Memory can be freed whilst still bound to resources, but those resources must not be used afterwards. Freeing a memory object releases the reference it held, if any, to its payload. If there are still any bound images or buffers, the memory object’s payload may not be immediately released by the implementation, but must be released by the time all bound images and buffers have been destroyed. Once all references to a payload are released, it is returned to the heap from which it was allocated.

Can you foresee any issues with retaining the device memory in the resource? Or devise a better approach?

**Comment by TheMrButcher** [comment]
I thought about introducing weak references and using it in MVKResource (weak references to MVKBuffers instead of unsafe raw pointers):
`auto buffCopies = _buffers;
for (auto& bufWeakRef : buffCopies) {
    if (auto buf = bufWeakRef.lock())
        buf->bindDeviceMemory(nullptr, 0);
}`
But your approach seems OK too. The main problem is that a lot of memory can be retained in unused descriptor sets. 'Destroyed' memory objects are still bound to 'destroyed' buffers but they all are retained.

**Comment by billhollings** [comment]
Sorry for the delay, but PR #1546 should fix this. Please retest, and if it fixes the issue you were having, please close this issue.

**Comment by billhollings** [comment]
Closing.
