### ISSUE TITLE
Zink

### ISSUE THREAD

**Issue by hilander1998** [KhronosGroup/MoltenVK#1332]
Does zink work yet and if so how does one use zink? I heard it was apart of moltenvk

**Comment by Spidy123222** [comment]
MoltenVK is part of Zink and seems they aim for MacOS only and not add it for IOS

**Comment by hilander1998** [comment]
But how does one use it ? In macos

**Comment by cdavis5e** [comment]
Zink and MoltenVK are two different projects; neither is a part of the other. Zink implements OpenGL on top of Vulkan and MoltenVK implements Vulkan on top of Metal. Because of this, on macOS Zink requires MoltenVK. If you want to know how to link Zink against MoltenVK, I think you should take it up with the Zink developers.

**Comment by ReaperOfSouls1909** [comment]
No answer at all but sure close it

**Comment by billhollings** [comment]
>No answer at all but sure close it

I'm not sure what you were looking for. As @cdavis5e explained, from what we understand, Zink can be layered on top of MoltenVK, but that is not something the MoltenVK team manages, and the best way to learn how that can be done is to move this question to the Zink team.

Consequently, I've closed this here, since it can't be answered here.
