### ISSUE TITLE
vkCube Regression - aspect ratio not preserved

### ISSUE THREAD

**Issue by richard-lunarg** [KhronosGroup/MoltenVK#1347]
vkCube no longer maintains a 1:1 aspect ratio when it is resized on macOS.

The behavior does not occur in an older SDK release (1.2.154.0), but does occur in newer releases. Replacing the MoltenVK dynamic library in an older release of vkCube that does not exhibit the problem then produces the resizing issue.  Most likely then it is a MoltenVK regression that occurred in the v1.1.1 release and forward.

**Comment by billhollings** [comment]
The reason for this is a change in how MoltenVK reports `VK_ERROR_OUT_OF_DATE_KHR` vs `VK_SUBOPTIMAL_KHR` for swapchains. 

In order to support a swapchain whose size doesn't match the underlying window, MoltenVK commit 891654d changed the reporting of a size mismatch between the two with `VK_SUBOPTIMAL_KHR`, instead of `VK_ERROR_OUT_OF_DATE_KHR`. Unfortunately a side effect of this was to report `VK_SUBOPTIMAL_KHR` on a window size change.

The Cube demo only resizes on `VK_ERROR_OUT_OF_DATE_KHR`, and has an explicit comment defining that return result to mean window resizing.

Therefore, the Cube demo swapchain is actually no longer getting resized as the window size changes, and the reason the aspect ratio changes is that the rendering is actually being stretched by the OS compositor, not the app or MoltenVK. This is also apparent because the framebuffer gets highly aliased and pixelated as it gets larger.

The Vulkan spec is not explicitly helpful here, because it defines the results as:

> -`VK_ERROR_OUT_OF_DATE_KHR` A surface has changed in such a way that it is no longer compatible with the swapchain, and further presentation requests using the swapchain will fail. Applications must query the new surface properties and recreate their swapchain if they wish to continue presenting to the surface.
>
> -`VK_SUBOPTIMAL_KHR` A swapchain no longer matches the surface properties exactly, but can still be used to present to the surface successfully.

The spec doesn't seem to explicitly address which of these is covered by window sizing.

As we can see from the current state of the demo, because of the OS compositor, the rendering does not "fail" (per `VK_ERROR_OUT_OF_DATE_KHR`) when the window is resized, and it clearly fits within the "can still be used to present to the surface successfully" (per `VK_SUBOPTIMAL_KHR`).

However, sticking to the letter of the law here clearly means that we have no real way of reporting a window size change, if the app only looks for `VK_ERROR_OUT_OF_DATE_KHR`.

So I'm up for suggestions about how to manage this, given the Vulkan spec requirements, and the OS compositor on Apple platforms.

**Comment by buzmeg** [comment]
This seems like an *application* bug.  Why doesn't it rebuild the swapchain on VK_SUBOPTIMAL_KHR which it gets to the present point?

Normally, the use of VK_SUBOPTIMAL_KHR is so that if you get this on acquire you can present *something* until you hit it again on present and then rebuild the swapchain so that window doesn't go completely dead.

The OS X behavior where it scales the previous contents indefinitely as you resize is by no means consistent behavior across OS and Vulkan implementations.  X11/Wayland, for example, make no attempt to scale the window with previous contents while resizing so if you don't draw something , you get a dead window or a window with garbage.

**Comment by buzmeg** [comment]
Looking further, this is absolutely a VkCube bug:

https://github.com/KhronosGroup/Vulkan-Tools/blob/4ee5f2a8bee064cdc338f80546b75cdebba171de/cube/cube.c#L1167
```
    if (err == VK_ERROR_OUT_OF_DATE_KHR) {
        // demo->swapchain is out of date (e.g. the window was resized) and
        // must be recreated:
        demo_resize(demo);
    } else if (err == VK_SUBOPTIMAL_KHR) {
        // demo->swapchain is not as optimal as it could be, but the platform's
        // presentation engine will still present the image correctly.
    }
```

It should redo the swapchain at the bottom if it is suboptimal.

**Comment by billhollings** [comment]
>Looking further, this is absolutely a VkCube bug:

@buzmeg Thanks for your input. I've [posted an issue](https://github.com/KhronosGroup/Vulkan-Tools/issues/506) to the VulkanTools repo.

**Comment by richard-lunarg** [comment]
Thanks everyone very much for the help on this. Makes perfect sense, and yeah, bugs aren't always as obvious as they appear ;-)

**Comment by buzmeg** [comment]
This should probably close due to https://github.com/KhronosGroup/Vulkan-Tools/pull/520

Thanks.

**Comment by richard-lunarg** [comment]
Indeed, I should have come back here and closed this issue once I verified that the fix was in. It was entirely a vkCube issue, nothing to do with MoltenVK after all.
