### ISSUE TITLE
Cube demo app does not seem to be resizing properly

### ISSUE THREAD

**Issue by mbechard** [KhronosGroup/MoltenVK#1453]
On an iMac running macOS 10.15.7. Nothing I do causes the swap chain to get recreated. I can resize the window, maximize it and it seems like it's just stretching the contents of the render to fill the window.
In particular I'm hoping to see how I'm supposed to handle resizing, along with how to handle moving the window from a retina display to a regular loDPI display, to see how the sample handles these cases.

**Comment by mbechard** [comment]
I think the behavior I saw would be resolved with #1455. Closing this one.

**Comment by billhollings** [comment]
> Nothing I do causes the swap chain to get recreated.

The Cube demo was modified back in June 2021 to handle `VK_SUBOPTIMAL_KHR` and resize accordingly. Perhaps you were running an older version when this was posted? You can use the error handling in the current version of `cube.c` as a template in your own apps.

As @cdavis5e points out, the use of `VK_SUBOPTIMAL_KHR` is intentional, as the behavior of `CAMetalLayer` is consistent with the description within the Vulkan spec of the difference between `VK_ERROR_OUT_OF_DATE_KHR` and `VK_SUBOPTIMAL_KHR`.
