### ISSUE TITLE
Missing OUT_OF_DATE return path for MVKSwapchain::getSurfaceStatus()?

### ISSUE THREAD

**Issue by mbechard** [KhronosGroup/MoltenVK#1455]
Shouldn't getSurfaceStatus() return OUT_OF_DATE if drawableSize does not equal the imageExtent the swap-chain was created with? For example dragging the window from a hiDPI to loDPI monitor will cause the drawableSize to change. getHasSurfaceSizeChanged() is returning false since the OS has correctly sized the drawableSize to the view's natural drawable size.

In my case I'm rendering to a multi-sampled buffer, then using vkCmdResolveImage to resolve the output into the swap chain image. I do my rendering to the resolution the swapchain has been last setup with, then vkAcquireNextImageKHR to get the swap chain image and resolve into it. However if the drawableSize has been changed since I started rendering, I need to know that the image I've acquired is a different size, since I can't resolve between images of different resolutions. I think I can likely avoid this by acquiring before starting rendering, but there seems to be value in acquiring at late as possible in some cases.
Or am I missing something?

**Comment by billhollings** [comment]
As discussed in your #1453 issue, the use of `VK_SUBOPTIMAL_KHR` is intentional, as the behavior of `CAMetalLayer` is consistent with the description within the Vulkan spec of the difference between `VK_ERROR_OUT_OF_DATE_KHR` and `VK_SUBOPTIMAL_KHR`.

The Cube demo was modified back in June 2021 to handle `VK_SUBOPTIMAL_KHR` and resize accordingly. You can use the error handling in the current version of `cube.c` as a template in your own apps.
