### ISSUE TITLE
Can we change the form of VkPhysicalDeviceProperties::deviceID for Apple GPUs?

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/MoltenVK#1486]
For Apple GPU's, MoltenVK currently sets `VkPhysicalDeviceProperties::deviceID` in the hex form `0xaMMX`, where `a` indicates an Apple SoC, `MM` is the SoC model number (08, 10...) and `X` is 1 for X version, 0 for other. The original idea was to try to map to the `A8, A10X...A15` nomenclature Apple was using for their SoCs, for transparent identification.

With the introduction of the M1 series of processors under macOS, and now iOS (recent iPad Pro), this naming structure gets confusing. For example, MoltenVK currently reports an M1 macOS as `0xa140`, because it supports the same functionality as the A14 GPU.

Apple distinguishes GPUs based on capabilities using the `MTLGPUFamily` enumeration (`MTLGPUFamilyApple7`, `MTLGPUFamilyApple6`, ...), and these apply to all platforms. For instance, both the `A14` and `M1`GPUs support `MTLGPUFamilyApple7 `.

Some options for moving forward with the `VkPhysicalDeviceProperties ::deviceID` nomenclature:

1. Leave it alone and continue to number just based on historic iOS `AXX` SoC's, even for the M1 series.

2. Introduce a second type of nomenclature for the M1 family (eg. `0xb010`). But this becomes arbitrary, and although we can assume M1 on macOS, it's not clear how we could distinguish M1 from say A14 on iPad Pro, without heroic efforts to extract system info.

3. Scrap the current nomenclature, and replace it with one simply based on the `MTLGPUFamily` enumeration, since that indicates relative GPU functionality, and is consistent on all platforms. For instance, we could create a `deviceID` that is basically just the number of the GPU functionality enumeration (`MTLGPUFamilyApple7` -> `0x7`...or maybe `0xad7` for Apple Device 7).

The third option is preferred because it is trivial to implement, is consistent across all platforms and GPU's, and maps to they way Apple identifies and distinguishes GPU functionality.

Does anyone use `VkPhysicalDeviceProperties::deviceID` in a way that will break if we make this change? Or is there reason to try to perform system query heroics to separately identify individual GPUs beyond Apple's `MTLGPUFamily` functionality designations?

**Comment by MennoVink** [comment]
Just making sure, this wont affect vk::PhysicalDeviceIDProperties::deviceUUID correct?

That field is needed to open the correct vulkan device depending on an opengl context's properties. I'm not sure how yet since EXT_external_objects is missing but that's a different issue.

I'm not using VkPhysicalDeviceProperties::deviceID, option 3 seems fine. But why not just the numeric value for the enum's value? ie 1007 for MTLGPUFamilyApple7?

**Comment by billhollings** [comment]
> Just making sure, this wont affect vk::PhysicalDeviceIDProperties::deviceUUID correct? That field is needed to open the correct vulkan device depending on an opengl context's properties. I'm not sure how yet since EXT_external_objects is missing but that's a different issue.

Yes. A change to `VkPhysicalDeviceProperties::deviceID` will also change the value of `VkPhysicalDeviceIDProperties::deviceUUID`, and would therefore break the Vulkan spec contract that...

> deviceUUID must be immutable for a given device across [...] driver versions [...].

You seem to indicate you're running some kind of combined Vulkan/OpenGL hybrid. Can you elaborate on why a change to the value of `VkPhysicalDeviceIDProperties::deviceUUID` will cause a problem with your environment? What is the value of `VkPhysicalDeviceIDProperties::deviceUUID` being used for?

> why not just the numeric value for the enum's value? ie 1007 for MTLGPUFamilyApple7

That is a good suggestion. Thanks.

**Comment by MennoVink** [comment]
I do run both Vulkan and OpenGL in the same application. Externally developed opengl based plugins need to keep running within an application ported over to Vulkan.

The situation on windows is hugely different than that on macOS. I think it could be useful to describe how it works on a platform with native Vulkan & OpenGL support though so bear with me.

**On windows:**
API interop is basically implemented as an external queue. There are extensions enabling support for creating objects to be accessible from the external queue, ie:
-https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_external_memory.html
-https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_external_memory_win32.html
-Also semaphores & fences. Other platforms got different type, ie fd on linux i believe.
When vulkan is done with an image, it's memory is transferred to the external queue (VK_QUEUE_FAMILY_EXTERNAL) at which point opengl can access it through a texture created with glTexStorageMem2DEXT
Using this texture, opengl can sample from it or render to it as it pleases. Eventually opengl will do a glSignalSemaphoreEXT call. Vulkan will transfer the the memory back from the external queue to lets say the graphics queue, waiting on the opengl semaphore.
This works great on single gpu machines, but on multi gpu (ie intel integrated + nvidia mobile laptops) some extra care needs to be taken. The shared memory is device-local, and thus if it's on the nvidia gpu the intel gpu cant access it. Since opengl has no way to select a device, vulkan needs to follow the gpu that the opengl context is using. On OpenGL i do this:
```
glGetUnsignedBytevEXT( GL_DRIVER_UUID_EXT, driverID.data() );
glGetUnsignedBytei_vEXT( GL_DEVICE_UUID_EXT, 0, deviceID.data() );
```
This retreives the driver id and device id which are needed to select the exact vulkan physical device that should be used. This is checked as:
```
memcmp( driverID.data(), physicalDevice.GetDeviceIDProperties().driverUUID, driverID.size() ) == 0 &&
memcmp( deviceID.data(), physicalDevice.GetDeviceIDProperties().deviceUUID, deviceID.size() ) == 0
```
If these values match that of the opengl context i know it's the same device and i can open that one. With this setup, memory stays on the gpu when going between apis and except for some some extra synchronization not much performance is lost.

**On macos:**
_Before i describe how i've implemented it on macos i would like to say it is incomplete. It works correctly on single gpu systems, but on multi gpu (ie mbp with intel + amd) i'm getting issues. My implementation is currently lacking device selection so probably i need to do something there._

None of the extensions used on windows (or their counterparts)  are available. We do however have core video which can be used for memory sharing. First create a CVPixelBufferRef. Then create a CVMetalTextureRef as well as a CVOpenGLTextureRef referencing this pixel buffer. From the metal texture's id im creating a vulkan image using vkSetMTLTextureMVK.
Since the external synchronization primitives are also not supported i needed something else. In testing it 'somehow' seemed to just work when submitting in order. So all vkQueueSubmits are flushed before opengl starts processing and after ogl is done i use a glFlush. I assumed this to work correctly because eventually macos seems to have just a single queue anyway so i can synchronize using just barriers.

Now, i'm not saying changing `vk::PhysicalDeviceIDProperties::deviceUUID` breaks anything for me right now. I'm not using it  on macos so as far as i'm concerned you can change it to whatever the spec allows. I dont think it necessarily needs to match `VkPhysicalDeviceProperties::deviceID` though. I was asking about it because I just wanted to know what the plans are for this field seeing that i need to do something with device selection and how important this field is for that on windows.

**Comment by billhollings** [comment]
Thanks for the background.

>I dont think it necessarily needs to match VkPhysicalDeviceProperties::deviceID though

The two values are distinct. But `deviceID` is one of the components that factor into the calculation of the `deviceUUID`...so changing the former will change the latter.
