### ISSUE TITLE
Pipeline layout compatibility bug?

### ISSUE THREAD

**Issue by TheMrButcher** [KhronosGroup/MoltenVK#1505]
I have 10+ pipelines which all have same push constant ranges and same descriptor set layout (camera UBO) as the first descriptor set layout. Some shaders don't actually use this descriptor set, but it's okay to add this descriptor set layout to make them all "compatible to set 0" as explained [here](https://www.khronos.org/registry/vulkan/specs/1.2/html/chap14.html#descriptorsets-compatibility). Using this feature I can bind my camera UBO only once at the start of render pass and it will be accessible to all pipelines. It works on Android and had been working on iOS before I tried to update MoltenVK to version 1.1.6 (previous version was 1.0.40).
After update I got graphical artifacts and crashes on asserts in Metal:
`validateFunctionArguments:3714: failed assertion 'Vertex Function(main0): missing buffer binding at index 1 for cameraUbo[0].'`

Using Metal debug tool I found out that some pipelines use different binding index for the camera UBO. Camera is buffer[2] in almost all pipelines but at least in one of them it is buffer[3]:
```
vertex main0_out main0(
    main0_in in [[stage_in]],
    constant CameraUbo& cameraUbo [[buffer(3)]],
    constant StylesUbo& stylesUbo [[buffer(4)]],
    constant PushConstants& pushConstants [[buffer(5)]])
```

The problem is that buffer[3] is always either unbound (which leads to crash) or is keeping garbage from previous pipeline (which leads to garbage on screen). This pipeline must use the same buffer[2] as camera UBO (as all other pipelines do), but instead it wants camera UBO as buffer[3]. All my pipeline layouts are “compatible for push constants” and "compatible for set 0", so there is no need in rebinding camera UBO after each pipeline change. But this rule is somehow broken in MoltenVK 1.1.6.

The broken pipeline has next resources:
Vertex shader:
```
layout(set = 0, binding = 0) uniform CameraUbo {
    mat4 mvp;
} cameraUbo;

layout(set = 1, binding = 0) uniform StylesUbo {
    ...
} stylesUbo;

layout (push_constant) uniform PushConstants
{
    ...
} pushConstants;
```
Fragment shader:
```
layout(set = 1, binding = 0) uniform StylesUbo {
    ... // same definition as in vertex shader
} stylesUbo;

layout (set = 2, binding = 0) uniform sampler2D textureSampler;
```

P.S. I can't get debug GPU workload in the moment of crash but it seems that there is another pipeline with different buffer index. Assertion message says that buffer[1] is not bound, so I assume that for some reason camera is buffer[1] in that pipeline.

**Comment by TheMrButcher** [comment]
Do you need more info?

**Comment by billhollings** [comment]
> Do you need more info?

Are you able to provide a stripped-down sample app so we can test here?

Alternately, it takes effort, but you could try to bisect MoltenVK Git commits, to try to isolate the MoltenVK code change that breaks descriptor set compatibility.

**Comment by James0124-rgb** [comment]
In `MVKPipelineLayout::MVKPipelineLayout(MVKDevice* device, const VkPipelineLayoutCreateInfo* pCreateInfo)`:
Does it seem to help if you pass the maximum amount of descriptor sets you would ever use (say 4 or 8 or whatever), instead of `pCreateInfo->setLayoutCount`, to `MVKShaderResourceBinding::addArgumentBuffers(uint32_t)` ?

Original:
https://github.com/KhronosGroup/MoltenVK/blob/101ea9eec158717c38c448d313d3c6452f8b327c/MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm#L123-L124

Proposed hack:
``` mm
_pushConstantsMTLResourceIndexes.addArgumentBuffers(8); // Or whatever amount sensible(?)
```

The original code seemed to result in incorrect Metal resource binding behavior when compatible VkPipelineLayout's with differing set counts are used across draw commands, not respecting Vulkan's _pipeline layout compatibility_ rules.

More specifically, in a sequence of commands (**no push constants involved**):
1. vkCmdBindPipeline: _pipeline A_ which has sets [0, 2]
1. vkCmdBindDescriptorSets: sets [0, 2]
1. _Draw command A_ using sets [0, 2]
1. vkCmdBindPipeline: _pipeline B_ which has sets [0, 3], of which [0, 2] are identical to those of _pipeline A_,
    meaning its VkPipelineLayout is "compatible for set 2" with that of _pipeline A_ as per the spec.
1. vkCmdBindDescriptorSets: set 3,
    not bothering to rebind sets [0, 2], leveraging _pipeline layout compatibility_; these binding must not be disturbed by this call to vkCmdBindDescriptorSets.
1. _Draw command B_ using sets [0, 3]

Paying attention to our theoretical UBO at (set=0, binding=0):
MoltenVK assigns MSL `buffer index == 3` for _pipeline A_; range [0, 2] is reserved for MTLBuffer's for push constants.
whereas it assigns MSL `buffer index == 4` for _pipeline B_; range [0, 3] is reserved for MTLBuffer's for push constants.

Relevant piece of code:
https://github.com/KhronosGroup/MoltenVK/blob/101ea9eec158717c38c448d313d3c6452f8b327c/MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm#L153-L154

At _Draw command A_, MoltenVK correctly binds the UBO buffer at MSL `buffer index == 3`.
At _Draw command B_, because we didn't bother rebinding sets [0, 2], MoltenVK doesn't know that the UBO buffer should now be bound at MSL `buffer index == 4`, so it remains bound at `buffer index == 3`,
which results in the shader reading the wrong UBO (bound at `buffer index == 4` for _Draw command A_) thus graphical artifacts, or in the app outright crashing,
not respecting _pipeline layout compatibility_.

The proposed hack makes the lowest MSL buffer index constant across all MVKPipeline's, working around this (apparent) bug.

I don't pretend to understand MoltenVK's codebase too much; I'd appreciate any correction.

**Comment by billhollings** [comment]
Closing.
