### ISSUE TITLE
vkCmdCopyImage and vkCmdBlitImage both return incorrect results on MacOS/iOS

### ISSUE THREAD

**Issue by floorman** [KhronosGroup/MoltenVK#156]
Hi,

As far as I can tell, the functions ```vkCmdCopyImage``` and ```vkCmdBlitImage``` both seem to return bad/incorrect texture data when trying to copy the backbuffer (get a screenshot) on MacOS and iOS.

On MacOS an empty texture with the correct dimensions is returned (0, 0, 0, 0) while on iOS this only happens if trying to get a screenshot on the very first frame, afterwards it appears to be fine. Using either of these methods on Windows works fine.

Stepping through Molten didn't seem to return anything immediately obvious.

I've uploaded a modified version of the cube demo C file to demonstrate the problem:
https://www.dropbox.com/s/blthbleqfulhds3/cube.c?dl=1

- The call to get the screenshot happens after ```vkQueuePresentKHR``` (line 1325).
- The code I'm using for actually grabbing the screen image is based on the Sascha Willems screenshot example and starts at line 690.
- I've also added some defines for changing between copy methods (starting at line 59) to hopefully make testing/reproducing easier. =)

I've been using breakpoints and looking at the data that comes back in the memory window in XCode as my results.

Thanks,

**Comment by billhollings** [comment]
@floorman 

Is there a reason why you capture the screenshot immediately _after_ the call to `vkQueuePresentKHR()` instead of immediately _before_?

The content will have already been written to the swapchain texture by then. The call to `vkQueuePresentKHR()` does not affect the content of the underlying swapchain texture...it simply tells the OS to use the image in the presentation compositor. 

On _macOS_ and _iOS_, swapchain resources (`MTLTextures` from `MTLDrawables`)  are a very scarce resource...and so MoltenVK very deliberately releases them as soon as `vkQueuePresentKHR()` is processed...so that they can be recycled by the Metal rendering engine.

This is why you are seeing an empty first image...and why subsequent images seem to be one frame behind. It is because by the time you capture the screen image...MoltenVK has released the underlying `MTLTexture`...and a different `MTLTexture` is then retrieved for use in the screenshot copy.

I have tested moving your `demo_process_screenshot()` call to just before `vkQueuePresentKHR`...and it seems to fix it...at least as far as the memory inspection indicates.

Can you test it further, and let me know if moving the screenshot call as I describe resolves the issue, please?

**Comment by floorman** [comment]
Hi Bill,

Moving the screenshot call as described solves the problem for me as well.

Thanks. =)
