### ISSUE TITLE
Using vkCmdBeginRenderPass with VK_KHR_dynamic_rendering still works.

### ISSUE THREAD

**Issue by spnda** [KhronosGroup/MoltenVK#1589]
The title sums it up pretty well. I can create a pipeline with the VK_KHR_dynamic_rendering features and set its render pass to null and then when using that pipeline, I can still call vkCmdBeginRenderPass with another render pass and it will work perfectly fine. It's an interesting quirk but I guess it's not *too bad*. Still something one should perhaps fix as subpasses and other small things might not work as expected.

**Comment by cdavis5e** [comment]
I don't see why we ought to fix that. Once you call `vkCmdBeginRenderPass()` with a dynamic-rendering pipeline, you've entered the wild land of undefined behavior, where literally anything goes. Catching apps doing such things is the role of the validation layer--not of implementations like MoltenVK. The driver's job is to just do what the app said as quickly as possible, crashes be damned--that's why validation was hoisted out in the first place.

**Comment by spnda** [comment]
true, I somehow forgot the validation layers even existed at all... 🤔 
obviously just a "driver quirk" and that should be fixed lol
