### ISSUE TITLE
iOS with notch, error renderTargetWidth (1125) must be <= minimum attachment width (1080).

### ISSUE THREAD

**Issue by timprepscius** [KhronosGroup/MoltenVK#1601]
Hey there,

I've been searching to see if someone else has run into this problem, and as of yet, I haven't found it.
I'm beginning my investigation of a "not dirty" fix.

I'm querying: (pseudo code)
```

physical_device = first of enumeratePhysicalDevices()
surface is created VK_STRUCTURE_TYPE_METAL_SURFACE_CREATE_INFO_EXT
surfaceCaps = getSurfaceCapabilitiesKHR(surface_); 

width_ = surfaceCaps.currentExtent.width;
height_ = surfaceCaps.currentExtent.height;

```

I'm using the width_ and height_ to instantiate the stencil and color and etc.

On iPhones with notches I'm seeing:

```
validateRenderPassDescriptor:991: failed assertion `RenderPass Descriptor Validation
renderTargetWidth (1125) must be <= minimum attachment width (1080).
renderTargetHeight (2436) must be <= minimum attachment height (2340).

```

I'm just starting to try to figure out exactly what the problem is.  If anyone has suggestions, or seen this in their own work, let me know!

**Comment by cdavis5e** [comment]
That message is saying that the render area cannot exceed the bounds of the smallest attachment. One of your attachments must be smaller than you expect.

We get the surface's `currentExtent` based on the `CAMetalLayer`'s `bounds` and `contentScale` properties. This is... not necessarily the same as the `drawableSize`, although we do set the `drawableSize` when you create the `VkSwapchainKHR` object. Are you passing the width and height you get back from `vkGetPhysicalDeviceSurfaceCapabilitiesKHR()` to `vkCreateSwapchainKHR()`?

It might be that the `CAMetalLayer`'s `drawableSize` is getting clamped because you don't indicate in your `Info.plist` that you support the notch. In that case, we might need to take a look at how we derive the surface extent, though I'd wonder why, in such a case, the layer's bounds aren't themselves clamped.

**Comment by timprepscius** [comment]
It is possible this is happening on the second frame - maybe the surface is
being re sized - because of some apple stuff with the Notch.

I put in code to handle surface resizing today (I wasn’t planning on
allowing for phone rotation, but now I do :-/)

I’ll know if this fixes things by the end of this week.

-Tim

**Comment by billhollings** [comment]
Closing, as it's been a while without feedback, and assuming the problem was resolved in the app usage.

**Comment by timprepscius** [comment]
Yes, i believe that my theory was correct.

I put in code to handle surface size changes and the problem went away.

**Comment by mohanataraj** [comment]
> Yes, i believe that my theory was correct.
> 
> I put in code to handle surface size changes and the problem went away.

thanks, this did help in my case as well, seems like setting my component size to 100% gave this error, very weird. Resolved by setting it lower than 100%...
