### ISSUE TITLE
Crash in vkDestroyDevice

### ISSUE THREAD

**Issue by MennoVink** [KhronosGroup/MoltenVK#1633]
After updating from 1.2.182 to 1.3.216 i now have a crash originating from vkDestroyDevice. Here's the stack:
<img width="1440" alt="Screenshot 2022-07-08 at 13 55 14" src="https://user-images.githubusercontent.com/26071817/177987399-a6fa43e0-6e7f-458c-b9bf-224eae921a42.png">

I'm running with specializedQueueFamilies enabled on an Intel(R) Iris(TM) Graphics 6100. It reports the following queue families:
-1x { Graphics | Compute | Transfer } timestampValidBits = 64
-1x { Graphics | Transfer } timestampValidBits = 64
-1x { Compute | Transfer } timestampValidBits = 64
-1x { Transfer } timestampValidBits = 64
I am opening all of them, but i'm only using the first. The crash occurs when the third queue family's _submissionCaptureScope is being ->destroy()'ed

If instead i specify vk::DeviceQueueCreateInfo::queueCount to be zero for all families except for the first one then this crash wont happen. So it might have something to do with opening a queue that never gets used, although the Graphics|Transfer queue does that as well but that gets destroyed without problems.

Any ideas what i could try to fix this?

**Comment by Valakor** [comment]
This looks to me like the same problem I'm having in #1598, which is likely due to a workaround in MoltenVK to fix an object retain count issue which has since been fixed by Apple (I think?). Presumably once #1632 gets merged then things will be fixed?

In my case the problem was resolved by creating 2 or fewer total queues (1 from 2 different families), though to be extra safe I'm only actually creating a single queue at the moment from family 0.
