### ISSUE TITLE
Add line width support as optional compilation macro

### ISSUE THREAD

**Issue by M1Minecraft** [KhronosGroup/MoltenVK#1657]
Hello, I'm trying to play No Man's Sky through Crossover and it says, "Does not support Wide Line". Does Metal 3 allow the use of Wide Lines or is it still not possible to implement?

**Comment by cdavis5e** [comment]
There is no *public* API for wide line support in Metal.

<br><br><br>
<sub>[This patch should make it work.](https://github.com/KhronosGroup/MoltenVK/files/9174751/0001-Support-wide-lines.patch.txt) I can't put this into `master`, though, because that would prevent apps bundling MoltenVK from submitting to the App Store. You're on your own here; we can provide no support. Maybe you can convince CW to put it in their fork; I no longer have much pull with them.</sub>

**Comment by M1Minecraft** [comment]
> There is no *public* API for wide line support in Metal.
> 
> 
> 
> <br><br><br>
> 
> <sub>[This patch should make it work.](https://github.com/KhronosGroup/MoltenVK/files/9174751/0001-Support-wide-lines.patch.txt) I can't put this into `master`, though, because that would prevent apps bundling MoltenVK from submitting to the App Store. You're on your own here; we can provide no support. Maybe you can convince CW to put it in their fork; I no longer have much pull with them.</sub>

I will try my best 😁, thank you for the support.

**Comment by M1Minecraft** [comment]
> There is no _public_ API for wide line support in Metal.
> 
> [This patch should make it work.](https://github.com/KhronosGroup/MoltenVK/files/9174751/0001-Support-wide-lines.patch.txt) I can't put this into `master`, though, because that would prevent apps bundling MoltenVK from submitting to the App Store. You're on your own here; we can provide no support. Maybe you can convince CW to put it in their fork; I no longer have much pull with them.

I'm kinda new to this and can't seem to figure out how to apply this patch? What steps would be required?

**Comment by cdavis5e** [comment]
> I'm kinda new to this and can't seem to figure out how to apply this patch? What steps would be required?

If you're using Git, `git apply 0001-Support-wide-lines.patch.txt` will work.

If not, use `patch -p1 <0001-Support-wide-lines.patch.txt`.

In both cases, you need to be in MoltenVK's root source directory.

**Comment by billhollings** [comment]
> [This patch should make it work.](https://github.com/KhronosGroup/MoltenVK/files/9174751/0001-Support-wide-lines.patch.txt) I can't put this into `master`, though, because that would prevent apps bundling MoltenVK from submitting to the App Store.

Interesting. I guess Apple might have added that private API when they needed to support OpenGL over Metal for M1? Any idea why they haven't made the API public?

**Comment by cdavis5e** [comment]
> Any idea why they haven't made the API public?

Nope. Maybe we need to put pressure on them to make it public.

**Comment by billhollings** [comment]
> Nope. Maybe we need to put pressure on them to make it public.

How did you learn of the private API call?

**Comment by cdavis5e** [comment]
> How did you learn of the private API call?

I looked at the Objective-C metadata in the Metal binary.

**Comment by Gcenx** [comment]
Would it be possible to import private APIs but have them disabled by default like say `MVK_ALLOW_METAL_FENCES`

**Comment by billhollings** [comment]
> Would it be possible to import private APIs but have them disabled by default like say `MVK_ALLOW_METAL_FENCES`

That's certainly a possible approach. These would be useful for macOS only, and only for Apps not distributed through the app store.

**Comment by rcaridade145** [comment]
How would Apple react towards MoltenVK if a user submits an app using MoltenVK with that patch? Wouldn't it be possible to simulate with , using mesh shaders? That being said alot of gaming console emulators would benefit from this.

**Comment by Gcenx** [comment]
> How would Apple react towards MoltenVK if a user submits an app using MoltenVK with that patch? Wouldn't it be possible to simulate with , using mesh shaders? That being said alot of gaming console emulators would benefit from this.

If your submitting to the App Store Apple would reject it due to the private API usage.

On the other hand if your referring to code-signing and notarizing that shouldn’t be a concern.

**Comment by Gcenx** [comment]
@cdavis5e do you happen to have any additional private api patches?

**Comment by cdavis5e** [comment]
> @cdavis5e do you happen to have any additional private api patches?

I have five private API patches in total. Some of them are quite ugly, and don't even work right. The logic op patch in particular, probably because I got the API constants for the logic operations wrong--those weren't in the ObjC metadata. The depth bounds patch also doesn't work quite right (it won't pass the CTS), probably because there's no support in Metal proper for it--it's a private method exported only by AMD's drivers.

The sample masks patch shouldn't be necessary; I wrote it before Google contributed a change to SPIRV-Cross to implement support for emulation in the fragment shader.

[0001-MVKPipeline-Support-framebuffer-logic-operations.patch.txt](https://github.com/KhronosGroup/MoltenVK/files/9203971/0001-MVKPipeline-Support-framebuffer-logic-operations.patch.txt)
[0002-MVKSampler-Support-LoD-bias.patch.txt](https://github.com/KhronosGroup/MoltenVK/files/9203972/0002-MVKSampler-Support-LoD-bias.patch.txt)
[0003-MVKPipeline-Support-sample-masks.patch.txt](https://github.com/KhronosGroup/MoltenVK/files/9203973/0003-MVKPipeline-Support-sample-masks.patch.txt)
[0004-Support-wide-lines.patch.txt](https://github.com/KhronosGroup/MoltenVK/files/9203974/0004-Support-wide-lines.patch.txt)
[0005-Support-the-depth-bounds-test.patch.txt](https://github.com/KhronosGroup/MoltenVK/files/9203975/0005-Support-the-depth-bounds-test.patch.txt)

**Comment by Rozzemak** [comment]
Yea this could be big. 
Can apple even prevent the usage of a "private api calls" outside of app store ?  

I dont quite get it..: here is a public library, but don't use undocumented entry points. These are not for you.

**Comment by Gcenx** [comment]
> Yea this could be big. Can apple even prevent the usage of a "private api calls" outside of app store ?

Release an update that requires a special entitlement that’s Apple only.

> I dont quite get it..: here is a public library, but don't use undocumented entry points. These are not for you.

If an API is private Apple doesn’t _need_ to guarantee it in anyway so can safely make breaking changes at any time without warning.

**Comment by spnda** [comment]
@cdavis5e May I ask which binaries you analysed to figure this out? I just tried to look for a Metal.dylib so I can analyse it with class-dump, but couldn't find one. Also, did you find anything else of interest, and have you checked with Metal 3?

On another note, though, would it perhaps be possible to put these patches using private API on a branch of MoltenVK for people who don't use the App Store and have it mostly just as a storage/testing of this private API?

**Comment by cdavis5e** [comment]
`/System/Library/Frameworks/Metal.framework/Metal`
`/System/Library/Extensions/AMDMTLBronzeDriver.bundle/Contents/MacOS/AMDMTLBronzeDriver`--this is the Metal driver for my discrete GPU; there are several other such `MTLDriver` bundles in that directory which might be interesting

There's also really kludgy support for custom border colors, as well as some support for transform feedback, and extra commands on `MTLBlitCommandEncoder` to encode texture clears and 32-bit buffer fills. I haven't looked at Metal 3 yet--my current laptop can't run macOS 13.

I suspect a lot of these are used by the Apple Silicon OpenGL driver, which is why they are present at all, but for whatever reason, Apple has neglected to make them public.

> On another note, though, would it perhaps be possible to put these patches using private API on a branch of MoltenVK for people who don't use the App Store and have it mostly just as a storage/testing of this private API?

If we put it behind a compile-time option, it should be possible to put it on `master`.

**Comment by spnda** [comment]
I've searched through my whole Mac and I cannot find any driver (even Intel and AMD ones). Searching in `/System/Library/Extensions/` I found a couple candidates, like e.g. `AGXMetal13_3` which would be the one for this M1, but the bundle is missing the executable and I cannot find any executable/library with the same name. There's also a `AppleMetalOpenGLRenderer`, which I would assume the OpenGL Driver to be, yet it also is missing its executable/library. `sudo find / -name AGXMetal13_3` yields nothing but a entry in the `Symbols` directory of Xcode. Trying to analyse that file with class-dump I just get `Error: Cannot find offset for address 0x202431d5668 in dataOffsetForAddress:`. Also, `/System/Library/Frameworks/Metal.framework/Metal` is a symlink to a location that doesn't exist. Perhaps something has changed with macOS 13 (or because this is a Beta?) and drivers like these are properly hidden? (I've also noticed I can't see hidden files for some weird reason). I'm not too experienced so I can't do much more here I'm afraid.

```
sean@iMac ~ % find / -name AGXMetal13_3 2>/dev/null  
/System/Volumes/Data/Users/sean/Library/Developer/Xcode/macOS DeviceSupport/13.0 (22A5295i) x86_64/Symbols/System/Library/Extensions/AGXMetal13_3.bundle/Contents/MacOS/AGXMetal13_3
/Users/sean/Library/Developer/Xcode/macOS DeviceSupport/13.0 (22A5295i) x86_64/Symbols/System/Library/Extensions/AGXMetal13_3.bundle/Contents/MacOS/AGXMetal13_3
```

**Comment by Gcenx** [comment]
@spnda that's getting off topic but modern versions of macOS no longer directly ship dylib files instead everything is inside dyld_shared_cache. There's guides and utilities to extract them.

**Comment by tellowkrinkle** [comment]
> The logic op patch in particular, probably because I got the API constants for the logic operations wrong--those weren't in the ObjC metadata.

Pretty sure you got it right.  It's just not supported on all GPUs.

Here's a test program I had for testing logic ops:
<details>
<summary>Test program</summary>

```objc
#import <Foundation/Foundation.h>
#import <Metal/Metal.h>

typedef NS_ENUM(NSUInteger, MTLLogicOperation) {
	MTLLogicOperationClear = 0,
	MTLLogicOperationSet = 1,
	MTLLogicOperationCopy = 2,
	MTLLogicOperationCopyInverted = 3,
	MTLLogicOperationNoOp = 4,
	MTLLogicOperationInvert = 5,
	MTLLogicOperationAnd = 6,
	MTLLogicOperationNand = 7,
	MTLLogicOperationOr = 8,
	MTLLogicOperationNor = 9,
	MTLLogicOperationXor = 10,
	MTLLogicOperationEquiv = 11,
	MTLLogicOperationAndReverse = 12,
	MTLLogicOperationAndInverted = 13,
	MTLLogicOperationOrReverse = 14,
	MTLLogicOperationOrInverted = 15,
};

@interface MTLRenderPipelineDescriptor()
- (void)setLogicOperationEnabled:(BOOL)enabled;
- (BOOL)isLogicOperationEnabled;
- (MTLLogicOperation)logicOperation;
- (void)setLogicOperation:(MTLLogicOperation)operation;
@end

NSString* libstring = @""
"#include <metal_stdlib>\n"
"using namespace metal;\n"
"\n"
"vertex float4 fullscreen_triangle(uint vid [[vertex_id]]) {\n"
"	return float4(vid & 1 ? 3 : -1, vid & 2 ? 3 : -1, 0, 1);\n"
"}\n"
"\n"
"fragment float4 fs_base() {\n"
"	return 0b1100 / 255.f;\n"
"}\n"
"fragment float4 fs_logic() {\n"
"	return 0b1010 / 255.f;\n"
"}\n";

int main(int argc, const char * argv[]) {
	@autoreleasepool {
		for (id<MTLDevice> gpu in MTLCopyAllDevices()) {
			id<MTLLibrary> lib = [gpu newLibraryWithSource:libstring options:nil error:nil];
			printf("Testing %s\n", [[gpu name] UTF8String]);
			MTLRenderPipelineDescriptor* desc = [MTLRenderPipelineDescriptor new];
			[desc setVertexFunction:[lib newFunctionWithName:@"fullscreen_triangle"]];
			[desc setFragmentFunction:[lib newFunctionWithName:@"fs_base"]];
			[desc.colorAttachments[0] setPixelFormat:MTLPixelFormatRGBA8Unorm];
			NSError* err = nil;
			id<MTLRenderPipelineState> pipeBase = [gpu newRenderPipelineStateWithDescriptor:desc error:&err];
			MTLTextureDescriptor* tdesc = [MTLTextureDescriptor texture2DDescriptorWithPixelFormat:MTLPixelFormatRGBA8Unorm width:16 height:1 mipmapped:NO];
			[tdesc setUsage:MTLTextureUsageRenderTarget];
			[tdesc setStorageMode:MTLStorageModePrivate];
			id<MTLTexture> tex = [gpu newTextureWithDescriptor:tdesc];
			id<MTLBuffer> buf = [gpu newBufferWithLength:4 options:MTLResourceStorageModeShared];
			MTLRenderPassDescriptor* rpdesc = [MTLRenderPassDescriptor new];
			id<MTLCommandQueue> q = [gpu newCommandQueue];
			[desc setLogicOperationEnabled:YES];
			[desc setFragmentFunction:[lib newFunctionWithName:@"fs_logic"]];
			for (int i = 0; i < 16; i++) {
				@autoreleasepool {
					rpdesc.colorAttachments[0].texture = tex;
					rpdesc.colorAttachments[0].loadAction = MTLLoadActionLoad;
					rpdesc.colorAttachments[0].storeAction = MTLStoreActionStore;
					[desc setLogicOperation:i];
					id<MTLRenderPipelineState> pipeLogic = [gpu newRenderPipelineStateWithDescriptor:desc error:&err];
					if (err) {
						printf("Failed to make logic op pipe: %s\n", [[err localizedDescription] UTF8String]);
					}
					id<MTLCommandBuffer> cb = [q commandBuffer];
					id<MTLRenderCommandEncoder> enc = [cb renderCommandEncoderWithDescriptor:rpdesc];
					[enc setRenderPipelineState:pipeBase];
					[enc drawPrimitives:MTLPrimitiveTypeTriangle vertexStart:0 vertexCount:3];
					[enc setRenderPipelineState:pipeLogic];
					[enc drawPrimitives:MTLPrimitiveTypeTriangle vertexStart:0 vertexCount:3];
					[enc endEncoding];
					id<MTLBlitCommandEncoder> download = [cb blitCommandEncoder];
					[download copyFromTexture:tex
					              sourceSlice:0
					              sourceLevel:0
					             sourceOrigin:MTLOriginMake(0, 0, 0)
					               sourceSize:MTLSizeMake(1, 1, 1)
					                 toBuffer:buf
					        destinationOffset:0
					   destinationBytesPerRow:4
					 destinationBytesPerImage:4];
					[download endEncoding];
					[cb commit];
					[cb waitUntilCompleted];
					unsigned int result = *(unsigned int*)[buf contents];
					printf("1100(D) <op %2d> 1010(S) → %c%c%c%c\n", i, result & 8 ? '1' : '0', result & 4 ? '1' : '0', result & 2 ? '1' : '0', result & 1 ? '1' : '0');
				}
			}
		}
	}
	return 0;
}
```
</details>

And its results on my laptop:
<details>
<summary>Results</summary>

```
Testing Intel(R) UHD Graphics 630
1100(D) <op  0> 1010(S) → 0000
1100(D) <op  1> 1010(S) → 1111
1100(D) <op  2> 1010(S) → 1010
1100(D) <op  3> 1010(S) → 0101
1100(D) <op  4> 1010(S) → 1100
1100(D) <op  5> 1010(S) → 0011
1100(D) <op  6> 1010(S) → 1000
1100(D) <op  7> 1010(S) → 0111
1100(D) <op  8> 1010(S) → 1110
1100(D) <op  9> 1010(S) → 0001
1100(D) <op 10> 1010(S) → 0110
1100(D) <op 11> 1010(S) → 1001
1100(D) <op 12> 1010(S) → 0010
1100(D) <op 13> 1010(S) → 0100
1100(D) <op 14> 1010(S) → 1011
1100(D) <op 15> 1010(S) → 1101
Testing AMD Radeon Pro 5600M
1100(D) <op  0> 1010(S) → 1010
1100(D) <op  1> 1010(S) → 1010
1100(D) <op  2> 1010(S) → 1010
1100(D) <op  3> 1010(S) → 1010
1100(D) <op  4> 1010(S) → 1010
1100(D) <op  5> 1010(S) → 1010
1100(D) <op  6> 1010(S) → 1010
1100(D) <op  7> 1010(S) → 1010
1100(D) <op  8> 1010(S) → 1010
1100(D) <op  9> 1010(S) → 1010
1100(D) <op 10> 1010(S) → 1010
1100(D) <op 11> 1010(S) → 1010
1100(D) <op 12> 1010(S) → 1010
1100(D) <op 13> 1010(S) → 1010
1100(D) <op 14> 1010(S) → 1010
1100(D) <op 15> 1010(S) → 1010
```
</details>

**Comment by andyoneal** [comment]
tried this on an M1 running 12.4 and another running 13beta4 and got the same results as the intel UHD.

**Comment by oscarbg** [comment]
@andyoneal @tellowkrinkle so conclusion seems to be Intel and Apple M1 Metal drivers support logic ops ext but not AMD Metal drivers, right?

**Comment by tellowkrinkle** [comment]
> so conclusion seems to be Intel and Apple M1 Metal drivers support logic ops ext but not AMD Metal drivers, right?

Only Skylake+.  Happens to be the same set of GPUs that support framebuffer fetch (though it isn't implemented with framebuffer fetch on Intel), making it not especially useful.  Using framebuffer fetch to calculate logic ops requires no private APIs and is officially supported on Apple GPUs (unofficial on Intel).

**Comment by IsaacMarovitz** [comment]
I wonder how bad the consequences would be of just stubbing this. Line width seems to be more like a stylistic choice than something fundamental to rendering.

**Comment by IsaacMarovitz** [comment]
Update, I built a version of MoltenVK that simply reported this feature as supported and got the game to open, but I quickly ran into a hang.
![](https://cdn.discordapp.com/attachments/1093182153560432711/1094706949267935424/Screenshot_2023-04-09_at_15.33.55.png)

Among expected errors about `vkCmdSetLineWidth()` not being supported were other errors about triangle fans

```
[mvk-error] VK_ERROR_FEATURE_NOT_PRESENT: Metal does not support triangle fans.
[mvk-error] VK_ERROR_FORMAT_NOT_SUPPORTED: VkPrimitiveTopology value 5 is not supported for rendering.
```

**Comment by IsaacMarovitz** [comment]
@M1Minecraft @billhollings Further investigation of No Man's Sky is even more puzzling. I logged out the value they're setting line width to, and it's just 1.0 😆 

![](https://cdn.discordapp.com/attachments/1093182153560432711/1094990318484586526/Screenshot_2023-04-10_at_10.20.00.png)

It may be worth changing MoltenVK to report as 'supporting' this feature, so games that 'require' it, like NMS, can launch and then just ignore the command and log an error if and when an app tries to actually change the line width to something != 1.0.

**Comment by billhollings** [comment]
> It may be worth changing MoltenVK to report as 'supporting' this feature, so games that 'require' it, like NMS, can launch and then just ignore the command and log an error if and when an app tries to actually change the line width to something != 1.0.

Thanks for doing the research about what NMS does. They may always be setting it to 1.0 because `wideLines` is not supported in MoltenVK. Or did you temporarily have MoltenVK return true for `wideLines`?

The spec is very clear that _"`wideLines` specifies whether lines with width other than 1.0 are supported"_. So although we could fake it out by enabling `wideLines` and setting `lineWidthRange` to `1.0 : 1.0`, and `lineWidthGranularity` to `1.0`, I imagine we would end up breaking the logic of a number of games that expected to set the line width to something that would be reasonably approximated.

**Comment by spnda** [comment]
The spec defines this VUID:
> VUID-vkCmdSetLineWidth-lineWidth-00788
If the wideLines feature is not enabled, lineWidth must be 1.0

So if NMS truly only ever sets lineWidth to 1.0 it really shouldn't error at wideLines being false.

**Comment by IsaacMarovitz** [comment]
> Thanks for doing the research about what NMS does. They may always be setting it to 1.0 because `wideLines` is not supported in MoltenVK. Or did you temporarily have MoltenVK return true for `wideLines`?

I specifically enabled the feature in MoltenVK configuration, as the game will not start unless the `VkPhysicalDeviceFeatures` reports that it is supported.

> Also, `vkCmdSetLineWidth()` does accept `1.0` without returning an error. When does NMS trigger the failure error? When `wideLines` returns `false`? Or when trying to use `vkCmdSetLineWidth()`?

The log message shown here is something I added just to double-check what values they are submitting to this function. I have also followed up by doing some analysis of the exe in Binary Ninja, and as far as I can tell, this is the only place they call `vkCmdSetLineWidth()`, and it is only ever with the default value of `1.0`. As a result I have reported this seemingly 'unnecessary' use of the feature to Hello Games, so who knows, maybe they'll patch it 😆

**Comment by IsaacMarovitz** [comment]
> So if NMS truly only ever sets lineWidth to 1.0 it really shouldn't error at wideLines being false. The Vulkan function can still be called safely with 1.0.

It's not that the game errors because of Vulkan. They specifically check what features are supported when they initialise their Vulkan backend, and the game will refuse to open if the requirements are not met.

![](https://cdn.discordapp.com/attachments/793156450821865515/1094682260973813871/Screenshot_2023-04-09_at_13.56.21.png)

**Comment by IsaacMarovitz** [comment]
It's also worth noting that while I can get to the loading screen with these workarounds the game crashes before it's done loading. It's not entirely clear if this is because of Wine, MoltenVK, or my Mac just simply running out of memory.

**Comment by spnda** [comment]
> It's not that the game errors because of Vulkan. They specifically check what features are supported when they initialise their Vulkan backend, and the game will refuse to open if the requirements are not met.

You obviously didn't understand what I am trying to say. Either:
- (1) The game does use values other than 1.0, unlike what you said you saw with the modified drivers' log.
- (2) The game is wrongly refusing because it actually doesn't need the wideLines feature and is actually submitting the calls for no reason, assuming it doesn't use anything other than 1.0.

What I was trying to say is that in the case you're right the game is wrongfully refusing to start and is technically violating the Vulkan spec and (besides the other issues) should not be concerned with the missing feature.

**Comment by IsaacMarovitz** [comment]
> You obviously didn't understand what I am trying to say. Either:
> 
> * (1) The game does use values other than 1.0, unlike what you said you saw with the modified drivers' log.
> * (2) The game is wrongly refusing because it actually doesn't need the wideLines feature and is actually submitting the calls for no reason, assuming it doesn't use anything other than 1.0.
> 
> What I was trying to say is that in the case you're right the game is wrongfully refusing to start and is technically violating the Vulkan spec and (besides the other issues) should not be concerned with the missing feature.

As far as I can tell through logs, and binary analysis, it is Option 2; their Vulkan implementation is flawed.

**Comment by italomandara** [comment]
Perhaps it uses wide lines in-game to get a sort of wireframe effect (maybe there's some visor in the game with that effect?) but it checks right at the beginning just in case.

**Comment by IsaacMarovitz** [comment]
> Perhaps it uses wide lines in-game to get a sort of wireframe effect (maybe there's some visor in the game with that effect?) but it checks right at the beginning just in case.

Binary Ninja could only find that one usage, so I'm not sure. One theory I had is that they're possibly using it in their dev tools but the check still exists on all devices.

**Comment by TellowKrinkle** [comment]
> ![](https://camo.githubusercontent.com/8ce17a8be133fd655e442f292df3ee2e453ee665d0a01484716cd4fa16b8f230/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f313039333138323135333536303433323731312f313039353336333239393631383539303735312f53637265656e73686f745f323032332d30342d31315f61745f31312e30322e32372e706e67) (Binary Ninja displays it as passing no arguments but I'm going to assume this is because of optimisation as the value is always the default)

Can you post the actual disassembly?  My guess is that it's actually passing the output of that _mm_cvtepi32_ps, which is an instruction that converts integers to floats, which would make sense in this case.  It would be pretty weird to have that instruction and not use its output, since it doesn't have any side effects.

**Comment by IsaacMarovitz** [comment]
> Can you post the actual disassembly? My guess is that it's actually passing the output of that _mm_cvtepi32_ps, which is an instruction that converts integers to floats, which would make sense in this case. It would be pretty weird to have that instruction and not use its output, since it doesn't have any side effects. The float input to `vkCmdSetLineWidth` will be in ~`xmm0`~`xmm1` if this is a windows program.

<img width="1552" alt="Screenshot 2023-04-13 at 08 17 54" src="https://user-images.githubusercontent.com/42140194/231755805-fee300de-fb25-4a71-9a8a-3e2756cafe5e.png">

Yep you're right. Still not really clear if the value ever is != 1.0

**Comment by billhollings** [comment]
PR #2137 fixes this.
