### ISSUE TITLE
Creating a Mach-o type - bundle with Vulkan dependency

### ISSUE THREAD

**Issue by bvdhruva** [KhronosGroup/MoltenVK#1685]
Hi all,

I have created a dylib bundle which is used by the application.

The dylib  bundle has been packaged with vulkan dylibs along with MoltenVK. Also have created the icd file as per document in resource folder. 

But how to make this to work as a single dylib entity instead of packaging all the dependencies again into app bundle?

**Comment by billhollings** [comment]
The MoltenVK distribution (`libMoltenVK.dylib`) is already a single `dylib` per platform.

Can you clarify what you are trying to do?

Do you want a single fat binary across all platforms? If so, unfortunately, that is not possible because a distinct `arm64` component exists on all platforms, and they can't be combined into a single fat library.

Or do you mean you want to bundle MoltenVK and the Vulkan SDK libraries into a single `dylib`? If so, I recommend you file this request with the [Vulkan SDK project](https://vulkan.lunarg.com/issue/home).

Or if you mean you want to bundle MoltenVK and your own library into a single `dylib`, you can do that by statically linking `MoltenVK.xcframework` to your own library and then build your `dylib` from that.

**Comment by bvdhruva** [comment]
Thanks Bill for the prompt response. 
I did realise that this is a request for [Vulkan SDK project], but since this is also a question of how we have to realise the path of moltenvk.dylib for a bundle which contains both Vulkan runtime and vulkan driver (moltenvk) as the path for moltenvk  is currently determined by App bundle( MoltenVK_icd.json inside a resources/vulkan/icd.d ) and not by the dylib bundle. Let me know if you have any pointers on achieving this.

My request is paragraph no 4 (Or do you mean you want to bundle MoltenVK and the Vulkan SDK libraries into a single dylib? If so, I recommend you file this request with the [Vulkan SDK project](https://vulkan.lunarg.com/issue/home).)

**Comment by billhollings** [comment]
> how we have to realise the path of moltenvk.dylib for a bundle which contains both Vulkan runtime and vulkan driver (moltenvk)

The `*icd.json` mechanism is defined by the Vulkan loader. The example `MoltenVK_icd.json` that appears in the MoltenVK distribution is compatible with that definition. So that question is also best handled by the Vulkan SDK team.
