### ISSUE TITLE
Defined VK_VERSION_1_3 causes linker problems while building for iOS

### ISSUE THREAD

**Issue by squadack** [KhronosGroup/MoltenVK#1708]
MoltenVK is an implementation of Vulkan 1.1 but the supplied headers define `VK_VERSION_1_3`, which causes [some](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator) libraries to expect a feature which isn't implemented. This causes an error while linking with MoltenVK framework for iOS, as it's missing some symbols (in my case `vkGetDeviceBufferMemoryRequirements` and `vkGetDeviceImageMemoryRequirements`).
Shouldn't MoltenVK define only versions up to `VK_VERSION_1_1`?

**Comment by spnda** [comment]
What the headers provide and what an implementation actually supports are two totally different and unrelated things. It's perfectly fine to use a 1.3 header with a 1.0 implementation, or vice versa. In this case, you are statically linking and VMA therefore tries to link to the prototype defined in the Vulkan header, even though it does not exist. Either you `#undef VK_VERSION_1_3` before you include the VMA header or you will have to dynamically load Vulkan function pointers at runtime using `vkGet*ProcAddr` (which I wholeheartedly recommend doing), otherwise the linker will try to find and link the functions from the driver directly, generating the errors you are receiving. If you use a variable like `volk` this process is extremely simple anyway.

And no, MoltenVK should definitely continue using up-to-date headers which will continue to include the `VK_VERSION_1_3` definition.

**Comment by billhollings** [comment]
As @spnda indicates, MoltenVK can't just use a header from `VK_VERSION_1_1`, as we need access to extension function and structure definitions beyond core functionality.

What happens to VMA with links to Vulkan extension functions that are not part of core? Those are also declared in the headers, but not implemented by MoltenVK. Do they not break the linkages from VMA?
