### ISSUE TITLE
`MTLRenderPassDescriptor`s leaking for `vkCmdBeginRenderPass` when recording from a worker thread with `prefillMetalCommandBuffers`

### ISSUE THREAD

**Issue by James2022-rgb** [KhronosGroup/MoltenVK#1729]
`MTLRenderPassDescriptor` objects allocated for `vkCmdBeginRenderPass` seem to leak if it's recorded from a worker thread with `prefillMetalCommandBuffers` enabled, presumably because its allocation and usage is not wrapped inside an autoreleasepool block,
resulting in gradually growing memory usage every frame.

I'm not knowledgeable in iOS/Cocoa ecosystem but I'm assuming the reason I don't see these leaks when not using `prefillMetalCommandBuffers` is because there's a default autoreleasepool block for the main thread,
which seems to suggest that these leaks would occur anyway if we did the `vkQueueSubmit` from a worker thread.

`MTL(Render|Blit)PassSampleBufferAttachmentDescriptor` objects also seem to leak if we're using timestamp queries, but I haven't investigated any deeper yet.

**Comment by billhollings** [comment]
This should be fixed in PR #1744. Please retest with that PR and close this issue if it fixes the issue you encountered.

@James2022-rgb
I've tried testing the leaks as best I can, but I've had trouble finding an app that has sufficient complexity **_and_** is configured with sufficient permissions to be  opened in the Xcode Instruments Leaks tool or command line leaks utility. I know this is last minute...but any testing you can do by end of day Monday Oct 17 would help get this into the SDK release due then.
