### ISSUE TITLE
Memory leak when not using @autoreleasepool

### ISSUE THREAD

**Issue by MennoVink** [KhronosGroup/MoltenVK#1732]
I have recently updated to 1.3.244. I am now experiencing a huge memory leak, about 100GB in 1 minute. I am using `prefillMetalCommandBuffers` and `specializedQueueFamilies`.
I noticed that if i place an @autoreleasepool around my frame then the leak is gone. Trying to figure out which call caused the issue i ended up at the vkCmdBeginRenderPass function. If i wrap just that call with an @autoreleasepool then i get an error that the Metal debug command encoder was released before any commands were recorded to it. Shouldn't this encoder be retained by the command buffer until i free that buffer?

I started digging into MVK a bit but i've got a few questions.

In `id<MTLBlitCommandEncoder> MVKCommandEncoder::getMTLBlitEncoder(MVKCommandUse cmdUse)`, why is the blit encoder not retained? If i place an @autoreleasepool around that then that pool errors out with the same issue. This already errors out way before i start rendering though, from the first `vkCmdCopyBufferToImage` call i'm making.

Similar question for `void MVKCommandEncoder::beginMetalRenderPass(MVKCommandUse cmdUse)` The render encoder isn't being retained either?

Finally in `void MVKCommandEncoder::encodeTimestampStageCounterSamples()` i'm seeing an autorelease but without it being in a pool?

**Comment by MennoVink** [comment]
![Screenshot 2022-10-04 at 18 40 09](https://user-images.githubusercontent.com/26071817/193877557-270f4534-2966-4d00-a24b-f94048512beb.png)
This is what instruments is showing for metal resource events. Does this mean that the render pass commands are retaining the images? That could cause a lot of memory to leak since i am destroying images but creating new ones each frame.

**Comment by billhollings** [comment]
This should be fixed in PR #1744. Please retest with that PR and close this issue if it fixes the issue you encountered.

@MennoVink
I've tried testing the leaks as best I can, but I've had trouble finding an app that has sufficient complexity **_and_** is configured with sufficient permissions to be  opened in the Xcode Instruments Leaks tool or command line leaks utility. I know this is last minute...but any testing you can do by end of day Monday Oct 17 would help get this into the SDK release due then.
