### ISSUE TITLE
`vkGetBufferDeviceAddressKHR` returns 0 on macOS 13.0, Vulkan SDK 1.3.231

### ISSUE THREAD

**Issue by AmesingFlank** [KhronosGroup/MoltenVK#1751]
I'm using vkGetBufferDeviceAddressKHR on macOS 13.0 Ventura, on VulkanSDK 1.3.231. I see that Vulkan reports buffer device address an a supported feature, but vkGetBufferDeviceAddressKHR always returns 0. Looking at MoltenVK's source code (https://github.com/KhronosGroup/MoltenVK/pull/1619/files), it looks like the function would only return the address if XCode 14 is used to build the library. Is it possible to fix/work-around this?

I also opened ticket for LunarG on this issue (https://vulkan.lunarg.com/issue/view/6357e5525df112ec593fac5e), but it was suggested that I raise it here instead.

**Comment by richard-lunarg** [comment]
I'm guessing you have to use an older version of XCode to support an older version of iOS? (I've had to do this before) Knowing what your minimum deployment target is might help with answering why XCode 14 was required.

**Comment by AmesingFlank** [comment]
I am happy to use XCode 14 and only target macOS 13+. However, it seem that VulkanSDK isn't built with XCode 14 enabled, so the library always returns 0 regardless of the macOS version. If this is the case then it looks like I have to build MoltenVK from source, instead of using the VulkanSDK.

**Comment by galad87** [comment]
The new macOS 13 sdk is bundled with Xcode 14.1 which is still a release candidate, maybe the VulkanSDK was built with Xcode 14 (which shipped the macOS 12 sdk).

**Comment by billhollings** [comment]
> The new macOS 13 sdk is bundled with Xcode 14.1 which is still a release candidate, maybe the VulkanSDK was built with Xcode 14 (which shipped the macOS 12 sdk).

Yes. Apple got a bit weird with the _Xcode 14_ release. Although the _iOS 16_ SDK was supported with _Xcode 14_, the _macOS 13_ SDK was not supported until _Xcode 14.1_, which as @galad87 helpfully points out, at this point, is still at RC status.

I deliberately did not go to the trouble of trying to separate _Xcode 14.1_ from _Xcode 14_, in the MoltenVK build macros, because I figured it was only a matter of a few weeks of dodginess. Unfortunately, the most recent SDK got packaged inside that interval.

> I am happy to use XCode 14 and only target macOS 13+.

Until the next SDK release, if anyone needs these features, use _Xcode 14.1+_ (if you're reading this while _Xcode 14.1_ is still in RC status, you'll have to [get it here](https://developer.apple.com/download/applications/)), then [build MoltenVK](https://github.com/KhronosGroup/MoltenVK#building) with it, and swap out (or symlink) the `<sdkpath>/MoltenVK` directory, and `<sdkpath>/macOS/lib/libMoltenVK.dylib` file (plus the `/usr/local/lib/libMoltenVK.dylib` file if you selected the global installation option in the VulkanSDK installer).

**Comment by richard-lunarg** [comment]
I can confirm the current SDK is build only using "released" tools and OS's at the time it was built (days ahead of release). The next SDK release will undoubtedly be using Ventura and XCode 14.1 or later at that time.

**Comment by AmesingFlank** [comment]
@richard-lunarg  
Hi! I noticed that XCode 14.1 has been officially released by Apple. Any chance we could get a new SDK release based on those?
