### ISSUE TITLE
 VkPrimitiveTopology value 5 is not supported

### ISSUE THREAD

**Issue by M1Minecraft** [KhronosGroup/MoltenVK#1799]
I'm trying to launch a game but I get a bunch of lines in the log stating that VkPrimitiveTopology value 5 is not supported and Metal does not support triangle fans. Is there any possible way to implement this into moltenVK?

[FullLog.txt](https://github.com/KhronosGroup/MoltenVK/files/10253275/FullLog.txt)

**Comment by M1Minecraft** [comment]
I think somone found a fix here: https://github.com/KhronosGroup/MoltenVK/issues/81

**Comment by rcaridade145** [comment]
RPCS3 the PS3 emulator "implemented" this a while back https://github.com/RPCS3/rpcs3/search?q=triangle+fans&type=commits

**Comment by billhollings** [comment]
Since the app is free to submit vertices and indices at any time, and MoltenVK would have no knowledge of whether the vertices had been massaged from fan to strip yet, to do this in MoltenVK, it would be best to massage the vertices or indexes using a compute shader that copied from one buffer to another before each triangle fan draw call, and then substitute the strip buffer in just before the actual Metal draw call.

At a minimum, this would involved breaking out of the Metal renderpass to run the compute shader. We do that for tessellation right now, so we have precedence for it, but it is something to consider from a structural and performance perspective.

Are triangle fans a must-have because some games that can't be modified at the source are using them?

**Comment by rcaridade145** [comment]
Afaik this was deprecated on D3D10+ . So we're talking about a subset of old games mainly. Emulators again afaik have implemented workarounds.
If it is an opensource game that should be taken upstream. @M1Minecraft what was the game?

**Comment by billhollings** [comment]
> Afaik this was deprecated on D3D10+ .

Yup. [Looks like it](https://en.wikipedia.org/wiki/Triangle_fan). Thanks for pointing this out.

**Comment by IsaacMarovitz** [comment]
> > Afaik this was deprecated on D3D10+ .
> 
> Yup. [Looks like it](https://en.wikipedia.org/wiki/Triangle_fan). Thanks for pointing this out.

No Man's Sky uses triangle fans

**Comment by billhollings** [comment]
PR # #1962 implements triangle fans.
