### ISSUE TITLE
VK_KHR_buffer_device_address on M1

### ISSUE THREAD

**Issue by maksym-pasichnyk** [KhronosGroup/MoltenVK#1840]
Can't enable VK_KHR_buffer_device_address or VK_EXT_buffer_device_address on Apple M1.
But I can get the buffer address using this code. 
Any reason, why VK_KHR_buffer_device_address is not supported on M1?

```
auto export_metal_buffer_info = vk::ExportMetalBufferInfoEXT()
    .setMemory(buffer_memory);

auto export_metal_objects_info = vk::ExportMetalObjectsInfoEXT()
    .setPNext(&export_metal_buffer_info);

device.exportMetalObjectsEXT(&export_metal_objects_info);
void* mtl_buffer = export_metal_buffer_info.mtlBuffer;

auto address = ((uint64_t(*)(id, SEL)) objc_msgSend)((id) mtl_buffer, sel_registerName("gpuAddress"));
```

**Comment by billhollings** [comment]
`VK_KHR_buffer_device_address` support requires:

- [x] Tier2 GPU argument buffer support (which you have with M1)
- [ ] macOS 13+ runtime
- [ ] MoltenVK must be built using Xcode 14+

Are all of those requirements met?

**Comment by maksym-pasichnyk** [comment]
I'm running MacOS 12.3.1, and Vulkan SDK from https://vulkan.lunarg.com
Why VK_KHR_buffer_device_address requires macOS 13+ runtime?
I will update my system and see if it works

**Comment by billhollings** [comment]
> Why VK_KHR_buffer_device_address requires macOS 13+ runtime?

That's when `gpuAddress` was [officially](https://developer.apple.com/documentation/metal/mtlbuffer/3929873-gpuaddress?language=objc) supported and made public.

It's quite likely that Apple added it prior to that as an internal private API, which is why you might be getting away with calling it in macOS 12.3.1 using your under-the-covers direct function call above, since you're bypassing the build system checks in doing that.

However, Apple guards the private API jealously, and will refuse apps in the App Store if it detects use of a private API call. We got burned by that a few years ago when another Apple API call got promoted from private to public.

**Comment by maksym-pasichnyk** [comment]
Thank, VK_KHR_buffer_device_address works after system update!
I think more extensions can be implemented using a private API.
Maybe add some env variable to enable them, but dissalow publishing on App Store?
As for me, I don't plan to publish, just learning Vulkan and want to experiment with it on my apple m1
