### ISSUE TITLE
Subpass self-dependency optimization

### ISSUE THREAD

**Issue by angelocarly** [KhronosGroup/MoltenVK#1879]
Hi, I'm currently implementing a programmable blending pipeline, think SVG documents, and am stumbling on some performance issues.

In order to achieve custom transparency I am using subpass self-dependencies. Every mesh samples the pixel value from the current render attachment and writes the result back into the same attachment. In order to protect from read/modify/write hazards a pipeline barrier is inserted in between draw.

This all works correctly, but I am running into performance issues when the object count gets high. Every time a self-dependency barrier is inserted, MoltenVK seems to split the affected draw calls up by restarting the Metal renderpass they're in. I would expect there to be a less overhead solution to this, like some kind of synchronisation within the same renderpass (note that I have any Metal experience and am not sure whether that's valid).
<img width="327" alt="image" src="https://user-images.githubusercontent.com/33165985/234618985-d8d30ce7-c187-4e0f-9d8b-e50e6026b4ff.png">

Is it expected behaviour from MoltenVK to perform self-dependency barriers by restarting the renderpass?

I've been thinking of alternative solutions to this, one might be to acquire the Metal objects and insert a Metal barrier myself to achieve this. But if that were to be a correct solution I wondered why MoltenVK doesn't do that instead, bringing me back here.

Thank you
Kind regards

**Comment by billhollings** [comment]
Because of the TBDR on Apple GPU's, those GPU's do not support barriers within a single Metal renderpass (basically a Vulkan subpass), nor do they support writing and reading from the same attachment in a Metal renderpass with implicit barriers, so we were forced to implement that particular barrier by ending one Metal renderpass and restarting another.

This functionality was added in [this PR](https://github.com/KhronosGroup/MoltenVK/pull/1415/files), which provides some further explanation.

**Comment by angelocarly** [comment]
Thanks you for the clarification!
