### ISSUE TITLE
VK_GOOGLE_display_timing: desired_present_time should be ignored if == 0

### ISSUE THREAD

**Issue by hrydgard** [KhronosGroup/MoltenVK#1988]
If you only want to use the extension to retrieve past presentation times, and not set a desired presentation time, things break a bit right now since `desired_present_time` is not ignored.

`bool hasPresentTime`;  should be split into

`bool hasPresentTime;`
and 
`bool queryPresentTime;`

and these two should be checked separately in `MVKPresentableSwapchainImage::presentCAMetalDrawable`.

**Comment by SRSaunders** [comment]
This should work properly in the upcoming MoltenVK 1.2.5 release, fixed by #1936.  Also see the pending 1.2.5 release notes at https://github.com/KhronosGroup/MoltenVK/blob/main/Docs/Whats_New.md

I have successfully used this pending fix to retrieve past presentation timings for the built-in Optick Profiler in the RBDoom3BFG game (see https://github.com/RobertBeckebans/RBDOOM-3-BFG/pull/780)

**Comment by hrydgard** [comment]
Oh excellent, I missed that. I'll close.
