### ISSUE TITLE
Release files for v1.2.5 changed without notice

### ISSUE THREAD

**Issue by makigumo** [KhronosGroup/MoltenVK#1998]
Hi!

It was noticed that the release files for https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.2.5 were changed and no notice could be found about this change. To rule out a malicious act could you please state for the record if this change was intentional?

Thanks.

related https://github.com/Homebrew/homebrew-core/pull/139860

**Comment by makigumo** [comment]
Thank you for the prompt clarification.

**Comment by ZhongRuoyu** [comment]
Thanks @makigumo for filing this issue. Hi @billhollings 👋 -- Homebrew maintainer here.

I read your comment here and would like to make sure if you were suggesting that releases can be retagged until they are non-RC. As mentioned in [Git's documentation](https://git-scm.com/docs/git-tag#_on_re_tagging), re-tagging is an "insane thing" that's strongly discouraged, because tags are meant to be final once they are published. A recommended way, as suggested in the documentation, would be to publish a new version instead. Would you consider marking RC releases with separate tags (like `v1.2.5-rc.1`) instead, and only publish stable tags (`v1.2.5`) when they are finalised?

Thanks for all your work maintaining the MoltenVK project!

**Comment by richard-lunarg** [comment]
For SDK builds internally, we create SDK branches, and then we'll update those branches if fixes are needed. On the final SDK build, we create the SDK tags. Perhaps we could do the same for MoltenVK? Create an SDK branch and after testing create the final tag?

**Comment by billhollings** [comment]
> Would you consider marking RC releases with separate tags (like v1.2.5-rc.1) instead, and only publish stable tags (v1.2.5) when they are finalised?

Yes. I was thinking along these lines after I posted above. This makes sense, and we'll aim to do that in future. We  can publish multiple RC tags, if needed, but won't publish the Release, until the final non-RC tag has been published, after the SDK is released.

**Comment by ZhongRuoyu** [comment]
That's great. Thanks @billhollings!
