### ISSUE TITLE
Blending not behaving properly on iOS 12 beta

### ISSUE THREAD

**Issue by mbarriault** [KhronosGroup/MoltenVK#209]
I recently updated my learner project (a particle generator) with some minor blending, which works as expected on macOS (High Sierra 10.13.6 on AMD 460, and Mojave beta 5 on Intel 5300), and looks like [this](https://share.icloud.com/photos/0691oylwX9L7sdvfGMh-bmRWA). 

On iOS (12 beta 5 on iPhone X and iPad Pro 10.5"), blending does not work as expected, and [this](
https://share.icloud.com/photos/0EHShiBA8YZzeKx62LWEMg6Vg) is rendered. Somehow, it appears to be "normalizing" the output colour to the alpha channel, as though it were inverting a pre-multiply pass.

However, I'd rather this tagged this as a question rather than bug, as I have no idea if the issue might be in MoltenVK, it's just as likely to be a beta bug. I'm keen to know if there is a general consensus on the status of MoltenVK on the beta, or if anybody has had issues with alpha blending that may provide insight. I do not have any non-beta devices to test on. I've stepped into MVKPipeline.mm to verify the relevant blending bits are indeed being connected as expected.

The blend state I'm creating with is trivial

    static const vk::PipelineColorBlendAttachmentState blendAttachment(true, vk::BlendFactor::eSrcAlpha, vk::BlendFactor::eOneMinusSrcAlpha, vk::BlendOp::eAdd, vk::BlendFactor::eOne, vk::BlendFactor::eZero, vk::BlendOp::eAdd, vk::ColorComponentFlagBits::eR | vk::ColorComponentFlagBits::eG | vk::ColorComponentFlagBits::eB | vk::ColorComponentFlagBits::eA);
    static const vk::PipelineColorBlendStateCreateInfo blendCreateInfo({}, false, vk::LogicOp::eClear, 1, &blendAttachment);
    graphicsPipeline.pipelineInfo.pColorBlendState = &blendCreateInfo;

**Comment by billhollings** [comment]
@mbarriault 

Have you tried this on a non-beta iOS version?

If you are unable to do so...do you have this as a simple project that you could share...and I can try it out on iOS 11?

**Comment by mbarriault** [comment]
It's currently hosted on a private BitBucket (git) repo, I can provide read access if you have an account.

**Comment by billhollings** [comment]
Sorry...I don't have a BitBucket account. Can you ZIP a pull for me and post it somewhere handy (eg- Dropbox)? I am assuming it contains nothing proprietary?

**Comment by mbarriault** [comment]
I emailed the zip file to you. It contains nothing proprietary, but nothing is licensed neither so I'm not comfortable sharing publicly for all to see yet.

**Comment by billhollings** [comment]
@mbarriault 

Thanks for submitting your app.

In your iOS Storyboard, you have the background color of the `VKView` set to White.

![screen shot 2018-08-07 at 1 32 42 pm](https://user-images.githubusercontent.com/356402/43792626-43dcf7da-9a47-11e8-9336-85bbeb37bfea.jpg)

Changing this background color to Black or Default (no color) fixes the issue.

When iOS composites the view...this background color is blended with the colors rendered to the pixels of the `CAMetalLayer`...based on the alpha values in the pixels of the `CAMetalLayer`.

Where your triangles fade, you blend the alpha value to the rendered texture, so the `CAMetalLayer` ends up with an alpha value of less than 1.0 in those pixels...allowing the White background color to leak (blend) through in those pixels.

The reason removing the alpha channel from the write mask also fixes the issue is because your renderpass clear color includes a 1.0 alpha value. By stopping your triangles from rendering the alpha channel, you leave the alpha value of the pixels in the `CAMetalLayer` at the cleared 1.0 value, which then stops the White background from blending through. You can verify this by changing the clear alpha value to something less than 1.0. The White background color then blends throughout the entire view.

If you need the `VKView` to have a White background color, you can also fix this by setting the blend OP of the alpha channel to `VK_BLEND_OP_MAX` which will cause the blend to leave the cleared 1.0 alpha value alone. Or you can resort to removing the alpha channel from the write mask...as you already discovered.

If this answer resolves your issue, please close this issue.

**Comment by mbarriault** [comment]
It indeed didn't need to be white, not sure how that got changed in the first place, but that is an impressive investigation, don't think I would've noticed that, thanks!
