### ISSUE TITLE
VK_EXT_metal_objects crashes (reference counting?)

### ISSUE THREAD

**Issue by MennoVink** [KhronosGroup/MoltenVK#2151]
I am compiling my app with ARC enabled. I'm by no means an obj-c expert but what i understand from the id<> type this automatically releases the referenced object. This means that any use of this extension crashes my app because MVK doesn't retain references before returning the ids.

If i modify MVK to contain retain calls on everything being returned from `MVKDevice::getMetalObjects` i do not get these crashes anymore.

I dont even have to use the returned object for this to crash. Calling this simple utility function in my app (from within @autoreleasepool) is enough to crash:

```
id< MTLDevice > VulkanMetalUtils::GetMetalDevice( const VulkanLogicalDevice& vkDevice )
{
	vk::StructureChain< vk::ExportMetalObjectsInfoEXT, vk::ExportMetalDeviceInfoEXT > exportInfoChain;
	vk::ExportMetalObjectsInfoEXT& exportInfo = exportInfoChain.get< vk::ExportMetalObjectsInfoEXT >();
	vk::ExportMetalDeviceInfoEXT& deviceInfo = exportInfoChain.get< vk::ExportMetalDeviceInfoEXT >();

	vkDevice.GetHandle().exportMetalObjectsEXT( &exportInfo );
	
	return deviceInfo.mtlDevice;
}
```

XCode wont allow be to add retain calls on my side as I'm compiling with ARC so retain/release calls are not allowed.

**Comment by billhollings** [comment]
I'm not able to replicate this in the Cube demo, where I enabled ARC, and added similar code to what you described:

```
@autoreleasepool {
	id<MTLDevice> mtlDev = self.getMetalDevice;
	NSLog(@"MTLDevice: %@", mtlDev.name);
}

-(id<MTLDevice>) getMetalDevice {
	id<MTLDevice> mtlDev;
	VkExportMetalDeviceInfoEXT mtlDevInfo = {VK_STRUCTURE_TYPE_EXPORT_METAL_DEVICE_INFO_EXT, nil, nil};
	VkExportMetalObjectsInfoEXT mtlObjInfo = {VK_STRUCTURE_TYPE_EXPORT_METAL_OBJECTS_INFO_EXT, &mtlDevInfo };
	vkExportMetalObjectsEXT(demo.device, &mtlObjInfo);
	return mtlDevInfo.mtlDevice;
}
``` 

All seems to work as expected, with no crashing.

The modified files are here, which also include some `__bridge` qualifiers that the Xcode compiler forced me to add to accommodate ARC, but don't seem to be related to `vkExportMetalObjectsEXT()` at all.

[Cube-patches.zip](https://github.com/KhronosGroup/MoltenVK/files/14213177/Cube-patches.zip)

Using these, please try to get Cube to fail in the same way your app is.

**Comment by MennoVink** [comment]
I think this wont reproduce the problem as it only releases one reference and MVK probably retains multiple references internally. I can make the cube crash either by writing a loop around the getMetalDevice call (i used 50 to get the crash inside the loop itself). Another way which is more representative to my situation is to do it each frame. If i move the getMetalDevice call to be done inside the DisplayLinkCallback the cube demo will also crash after several frames.

**Comment by billhollings** [comment]
I've done some [research](https://clang.llvm.org/docs/AutomaticReferenceCounting.html#c-c-compatibility-for-structs-and-unions-with-non-trivial-members) on how ARC is treating these returned objects.

ARC supports passing Objective-C objects in C-structs, but it [defaults](https://clang.llvm.org/docs/AutomaticReferenceCounting.html#objects) to attaching the `__strong` ownership qualifier to the struct member declarations (and actually all variables), which means...

> Likewise, a function returning a non-trivial struct may be written in ARC and called from non-ARC or vice-versa. The convention for this always transfers ownership of objects stored in __strong fields from the callee to the caller, and so callees must initialize such fields with +1 references, and callers must balance that +1 by releasing or transferring them.

...which is why MoltenVK retaining the objects before returning them fixes this in ARC apps (but unfortunately breaks it in non-ARC apps).

It turns out the way to fix this, for both ARC and non-ARC apps, is to qualify the ownership of these struct members as `__unsafe_unretained` in their declarations, which instructs ARC to treat them as it would an `assign` property qualifier.

The place to do this is in `vulkan_metal.h`. Can you try applying the following patch to the `External/Vulkan-Headers` repository, please?

[mtl-obj-unret.diff.zip](https://github.com/KhronosGroup/MoltenVK/files/14844689/mtl-obj-unret.diff.zip)

If that fixes the problem, I will initiate a PR into Khronos, to get these changes integrated into the `VK_EXT_metal_objects` extension.

**Comment by billhollings** [comment]
PR #2200 fixes this issue.
