### ISSUE TITLE
Wrong rounding/conversion from Floating-Point to Normalized Fixed-Point in ClearValue

### ISSUE THREAD

**Issue by PolarNick239** [KhronosGroup/MoltenVK#2272]
Hi,

If I don't miss anything - there are strange behaivor in case when we have uint8  frambebuffer cleared with ```vec4(238.07, 240.05, 240.06, 255.00)/255.0``` color - it is converted into **(239, 239, 240)**, while I expect it to be converted to **(238, 240, 240)**.

# Steps to reproduce:

1) Download Vulkan examples from https://github.com/SaschaWillems/Vulkan
2) Change https://github.com/SaschaWillems/Vulkan/blob/8b4ee5903364c86bc4d572b53ee8f1ac80501851/base/vulkanexamplebase.h#L203 to:

```C++
	VkClearColorValue defaultClearColor = { { 238.07f/255.0f, 240.05f/255.0f, 240.06f/255.0f, 1.0f } };
```
3) Launch ```gears```
4) Launch ```Digital Colour Meter``` (from Spotlight Search)
5) Check any white pixel from background in gears window:

![image](https://github.com/KhronosGroup/MoltenVK/assets/1218605/78cfe9cd-d2aa-4206-a129-c5a9d8585958)

# Found:

Strange rounding/conversion:

1) 238.07 -> **239**
2) 240.05 -> **239**
3) 240.06 -> 240

# Expected:

If I understand correctly - w.r.t. [specification (3.10.2. Conversion From Floating-Point to Normalized Fixed-Point)](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap3.html#fundamentals-fpfixedconv) - results **should** (which [mean that there may exist valid reasons in particular circumstances to ignore a particular item, but the full implications must be understood and carefully weighed before choosing a different course](https://www.ietf.org/rfc/rfc2119.txt)) be:

1) 238.07 -> **238**
2) 240.05 -> **240**
3) 240.06 -> 240

Is this expected or is this a bug?

If this is an expected feature - is it possible to know the reasoning behind this decision in the implementation?

# My setup

MacBook Pro 2017 + Ventura 13.6.4 + AMD Pro 560 + MoltenVK 1.3.283

**Comment by billhollings** [comment]
On my system, using the Digital Color Meter, I'm actually seeing the correct values:

![Screenshot 2024-08-28 at 4 31 37 PM](https://github.com/user-attachments/assets/19c72320-37a6-48b7-8253-26dbec7749eb)

However, I'm not sure using Digital Color Meter is the best way of testing rendered colours, because it likely depends on things like the CoreGraphics compositor on your system.

A better method for determining what is being rendered is to use GPU Trace to capture the render and then check the pixels being rendered to the render attachment. Here, the float values 0.9333 & 0.9411 correspond to the unorm values 238 & 240 values.

![Screenshot 2024-08-28 at 4 49 18 PM](https://github.com/user-attachments/assets/039bd42a-8977-4914-9899-aa0d429214fb)

**Comment by PolarNick239** [comment]
Thank you, so at least on more fresh AMD M3 GPUs (and probable M1/M2 too) it works fine.

I agree that Digital Color Meter is not reliable, initially the problem was detected with unit-test in more complex application (unit-test loads attachment results from VRAM into RAM and checking results).

I tried to use GPU Trace (thank you for screenshots!) and it seems that I was able to evaluate experiment in a way similar to your's:

![image](https://github.com/user-attachments/assets/3384ea1d-b807-4189-91a0-9fd4a3823910)

Sadly, on AMD 560 I got **0.9372, 0.9411, 0.9450 - i.e. 239, 240, 241**.

Probably this is driver-related problem specific for AMD GPUs and is irrelevant to MoltenVK (or may be I miss something and my experiment is incorrect).

MacBook Pro 2017 + Ventura 13.6.4 + AMD Pro 560 + MoltenVK 1.3.283 + Xcode 15.2
