### ISSUE TITLE
Will allow you to set invalid Pixel Formats.

### ISSUE THREAD

**Issue by burito** [KhronosGroup/MoltenVK#282]
MoltenVK uses a CAMetalLayer for rendering, which according to [Apple](https://developer.apple.com/documentation/quartzcore/cametallayer/1478155-pixelformat) only supports 5 different pixel formats.

Setting for example ```VK_FORMAT_R8G8B8A8_UNORM``` will result in a CAMetalLayerInvalid Exception, with the text "invalid pixel format 70" (70 is the value of [MTLPixelFormat.rgba8Unorm](https://developer.apple.com/documentation/metal/mtlpixelformat/rgba8unorm)).

I'm submitting this issue, as setting something like ```VK_FORMAT_R64G64B64A64_UINT``` will print the sensible message...

    [***MoltenVK ERROR***] VK_ERROR_FORMAT_NOT_SUPPORTED: VkFormat VK_FORMAT_R64G64B64A64_UINT is not supported on this platform.

And *then* throw a CAMetalLayerInvalid exception, which to me seems like preferred behaviour.

**Comment by burito** [comment]
Oops, was already fixed in current version, but not in the LunarG version.

**Comment by billhollings** [comment]
@burito All recent MoltenVK updates will appear in the next LunarG SDK...which should be released sometime next week.

**Comment by billhollings** [comment]
@burito 

Actually...looking at this further...I don't see any recent changes in that behaviour within MoltenVK...so I don't know what changes you are seeing between the current SDK and current MoltenVK.

However...as per the Vulkan spec...the image format you use when creating a swapchain must only be one of the values returned from `vkGetPhysicalDeviceSurfaceFormatsKHR()`, which does not include `VK_FORMAT_R8G8B8A8_UNORM`.

Because of that requirement within the Vulkan spec, MoltenVK does not attempt to re-validate the image format when the swapchain is created, and you are encountering documented undefined behaviour as a result.

The reason you were seeing the error for `VK_FORMAT_R64G64B64A64_UINT` is because that pixel format is simply not supported by Apple.

**Comment by burito** [comment]
Thank you kindly for your help.

I did notice that vkGetPhysicalDeviceSurfaceFormatsKHR() functions on
MoltenVK without the "VK_KHR_surface" extension enabled. The Nvidia drivers
on Windows and Linux do not do this. Is this a level of pedantry that
MoltenVK is looking for?

**Comment by burito** [comment]
Ah my apologies Mr Hollings, I'm not being clear.

Retrieving supported surface formats is part of the VK_KHR_surface
extension, and at least on the Nvidia drivers on Windows & Linux, without
requesting that extension, vkGetPhysicalDeviceSurfaceFormatsKHR() will
return no formats.

Is this form of rigid adherence to the standard something you want?

**Comment by billhollings** [comment]
@burito 

Maybe I'm not understanding what you are trying to do.

Where are you encountering this format issue? Are you trying to create a swapchain on a surface on macOS or iOS? That is where the `CAMetalLayer` would come into play.

If so...the `VK_MVK_ios_surface`, `VK_MVK_macos_surface`, and `VK_KHR_swapchain` extensions all require the `VK_KHR_surface` to be enabled.

Or are you experiencing this issue in some other use case.

And in your question about adherence...I'm not clear whether you are suggesting that MoltenVK is too rigid...or not rigid enough...in it's adherence to the Vulkan standard, relative to other implementations.
