### ISSUE TITLE
Supports MoltenVK drawing points?

### ISSUE THREAD

**Issue by brainiac13** [KhronosGroup/MoltenVK#311]
My Problem:
I use the Cube Demo. I enabled the fillModeNonSolid DeviceFeature in the DeviceCreateInfo.
The feature list says it is supported on my Device (GTX 760)
When I set the poligonMode in my rasterizer to VK_POLIGON_MODE_POINT I only get the lines (wireframe) and not the points. As if it is set to VK_POLIGON_MODE_LINE.

**Comment by billhollings** [comment]
I'm able to replicate this...and working on a fix.

**Comment by billhollings** [comment]
@brainiac13 

This is fixed in PR #313. Please retest and close this issue if it fixes it.

Per the Vulkan spec, in your vertex shader, you need to specify a value for the `PointSize` builtin (if coming from GLSL, by setting a value in the `gl_PointSize` builtin variable). You can leave this value set in the shader to test both `FILL` and `POINT` modes.

The MoltenVK _Cube Demo_ does not set a value for the `PointSize` (`gl_PointSize`) builtin variable in its vertex shader...so you will have to modify it if you want to use that demo to test this feature.

**Comment by brainiac13** [comment]
have you tested the PointSize?
I added the following line in the cube.vert main()
gl_PointSize = 150.0;
But the Points are only one pixel 

GTX 760 says:
VkPhysicalDeviceFeatures
largePoints = 1
VkPhysicalDeviceLimits:
pointSizeRange[0]                       = 1.000000
pointSizeRange[1]                       = 511.000000

**Comment by billhollings** [comment]
@brainiac13 

Yes...MoltenVK uses the `PointSize/gl_PointSize` built-in value.

Unfortunately, `cube.c` does not compile the shader `cube.vert`...so changes to that file will have no effect.

The vertex shader is loaded as SPIR-V code from `cube.vert.inc`: 

```
static void demo_prepare_vs(struct demo *demo) {
    const uint32_t vs_code[] = {
#include "cube.vert.inc"
    };
    demo->vert_shader_module = demo_prepare_shader_module(demo, vs_code, sizeof(vs_code));
}
```

To test this update, I modified `cube.vert`...ran it through the standalone `MoltenVKShaderConverter` tool...and then used `xxd` to create a header file which I then imported into a modified `cube.c`. Or you could modify `cube.c` to load the SPIR-V from a file. Or use a more flexible and dynamic example.

BTW...you can see how the SPIR-V is being converted to MSL by compiling MoltenVK in Debug mode...and MoltenVK will log the SPIR-V, the MSL, and an estimate of the original GLSL.

**Comment by brainiac13** [comment]
Perfect, it works. Good hint with compiling MoltenVK in Debug.
