### ISSUE TITLE
Memory allocations during rendering

### ISSUE THREAD

**Issue by aerofly** [KhronosGroup/MoltenVK#350]
Our rendering engine is optimised so that we don't use or try to minimise dynamic memory allocations during rendering to keep those system calls low and to avoid memory fragmentation on badly implemented memory allocators.

Using MoltenVK we saw that quite a few memory allocations happen while rendering a frame. In our specific use case it was around 200 to 400 of them.

Looking at the MoltenVK source code it's quite easy to fix some of the major allocations/deallocations that take place. If it's ok we can submit a pull request that reduces those calls, but some of the allocations are hard to fix on our side, due to limited knowledge on how MoltenVK works internally. For example some MoltenVK objects are allocated/deallocated each frame instead of being reused.

If its ok we would go ahead and try to submit a pull request, unless you say those dynamic memory allocations are no issue at all and do not affect memory fragmentation and/or runtime performance on MacOS and iOS.

**Comment by billhollings** [comment]
@aerofly 

Many of the existing render-time objects...like  instances of `MVKCommand` subclasses...are already pooled and reused. If there are other allocations that could be further pooled...all the better. Where have you identified such allocations?

We definitely encourage PR submissions! If you do want to work on this...and if you will be pooling...have a look at the existing `MVKObjectPool` class hierarchy...and make use of, or extend, that...instead of reinventing the wheel. And for consistency...please respect the existing coding style.

Thanks!

**Comment by aerofly** [comment]
@billhollings 

Most of the allocations come from the usage of std::vector or std::list. With some real minor tweaks, I could replace those classes with either a fixed size containers ( if its guaranteed that those have an actual maximum size due to Vulcan specifications ) or we add some internal storage capacity before allocations on the heap are used. The use of std::list is not necessary if the length of the list is short. 

As for the destroyed MVK objects just a few examples:

1. I saw that in the function
void MVKQueueCommandBufferSubmission::finish()
when you call this->destroy() the destructors of std::vector get called. Again, my recommendation here would be to replace the two std::vector either with a simple drop in replacement that features some internal storage or you give the std::vector class its own allocator, but that is a little overkill in my eyes.

2. MVKFenceSitter::~MVKFenceSitter() uses a std::vector as a temporary object.

3. MVKCommandEncoder::~MVKCommandEncoder() is also called each frame and uses a std::vector internally.

Again, I can make a pull request and add a simple version of std::vector that features some internal storage. You should then get the idea and maybe replace the other occurrences of std::vector with the new class.

If it's ok to use C++17 this I will just drop in our class we use internally and you can tune that one to your needs.

Of course I will try to respect the coding style and formatting.

**Comment by billhollings** [comment]
Ah...I understand.

1. I think what I'd prefer to do with `MVKQueueCommandBufferSubmission` is allocate them from a pool...as is done with `MVKCommands`...and other objects. That would deal with the several collections that each of this hold...because they could be resized via `reserve()` rather than allocated and deallocated. I can take care of these.

2. We could flip this temp vector to a stack-allocated `MVKFence*` array.

3. Yes...`MVKCommandEncoder` is a complicated object...and several of the objects it contains have collections. This might be a good case for your plug-in vector class. 

I am also a little wary of introducing hard limits to collection sizes. Some...like a vector of viewports... will work with a reasonable fixed size...but others may not have reasonable hard-coded size limits...but I'm happy to hear your thoughts on the `MVKCommandEncoderState` collections.

How do your replacement collection classes pre-allocate internal storage? Do the constructors take a "pre-sizing" value? Or do all the collections pre-size to a fixed value?

I'm not sure that we can jump to C++17 yet just to solve this issue. Different users have different build environment...and I don't want to block anyone out without due diligence. Why does it need to be C++17?

**Comment by aerofly** [comment]
The more you can change on your side, the better. Again, I do not have the inside into the code as you do, so anything you can fix yourself is much better than my fixes. I am just trying to make some suggestions on how to reduce or eliminate those allocations.

The vector class with a pre-allocated internal storage is only needed if you need to construct objects with std::vector members dynamically. Again, if you switch those objects to your pool method, most allocations might already be gone.

If you need dynamic std::vector, I recommend to use the custom vector class with a little bit of pre-allocated internal storage, so that allocations are not needed in most situations. I can try to convert our class we use in our projects to a format compatible with your source code.

As for C++17, its no big issue. Using C++17, the source code size of the custom vector class is smaller, but one can achieve the same with C++11 as well.

**Comment by aerofly** [comment]
I have created a small pull request that shows the enhancements I was talking about. Again, it drops the number of heap allocations from a few thousands per frame to a around 100 in our special use case. Let me know if you have any further questions here or would like to make adjustments to the code.

**Comment by aerofly** [comment]
Most enhancements discussed here have already been merged into MoltenVK by now.
