### ISSUE TITLE
Add additional queue families to provide dedicated queue types

### ISSUE THREAD

**Issue by petereichinger** [KhronosGroup/MoltenVK#441]
I have macOS 10.14 with an AMD Radeon Pro 560X.
Today I updated from 1.1.82.1 to 1.1.91.1 and my application immediately stopped working since it expects at least 3 queues (one general, one dedicated for transfers and compute each). I probably should handle the case that only 1 queue is available but nonetheless there shouldn't be any differences between the versions.

With version 1.1.82.1 vulkaninfo says there are 8 queues for compute, transfer and graphics.
There is only 1in 1.1.91.1 .

I tried 1.1.85.0 as well and it shows only 1 queue.

**Comment by Usami-Renko** [comment]
It was mentioned in the release of [MoltenVK v1.0.22](https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.0.22). You have to adapt your code to one queue.

**Comment by billhollings** [comment]
In Vulkan, CommandBuffers are associated with Queue Families. In Metal, they are associated with Queues.

In order to be able to pre-process a Vulkan CommandBuffer on the application thread that it is filled on before it is formally submitted to a Queue, it is necessary to map each Vulkan CommandBuffer with the MTLQueue it will be later submitted to. Hence the need to restrict each Queue Family to a single MTLQueue.

In Metal, all queues are capable of all three graphics, transfer, and compute functionalities. In Vulkan, these functionalities are defined by Queue Families.

So if there is a real need to separate queue functionality between graphics, transfer, and compute...we could easily add additional Queue Families in MoltenVK. For example...MoltenVK could define three Queue Families (each still containing a single queue):

1. `VK_QUEUE_GRAPHICS_BIT | VK_QUEUE_COMPUTE_BIT | VK_QUEUE_TRANSFER_BIT`
2. `VK_QUEUE_TRANSFER_BIT`
3. `VK_QUEUE_COMPUTE_BIT`

**Comment by petereichinger** [comment]
The best thing would be both of course but for me personally currently a queue for each type and one queue that can do everything would be enough.

As a side question: 
Some Nvidia cards have dedicated queues for transfers (and the expensive ones even for compute) and when writing applications these dedicated queues can be used instead of the generic ones for faster execution (didn't verify the last part, just read it somewhere). Would be awesome for MoltenVK to support dedicated queues.

**Comment by billhollings** [comment]
@petereichinger  Thanks for the input.

Regarding specialized hardware queue types...MoltenVK is restricted to behaviour that is provided by Metal. When Metal exposes that type of queue identification MoltenVK will be able to expose it and make use of it in turn.

In the meantime...MoltenVK can certainly provide more queues via dedicated queue families. Again...it will be up to Metal whether it makes use of them under the covers. Some hardware only supports a single physical queue.

**Comment by billhollings** [comment]
I'm changing the name of this issue and making it an enhancement.

**Comment by billhollings** [comment]
Enhancement added in PR #450.
