### ISSUE TITLE
[MoltenVK] Assertion  when  clearing only the depth buffer 

### ISSUE THREAD

**Issue by elix22** [KhronosGroup/MoltenVK#487]
I am getting an exception (Metal API validation enabled)
When clearing only the Depth buffer of a texture format MTLPixelFormatDepth32Float_Stencil8.
In that case the stencilAttachment in not filled and is causing an assertion.

I made a fix that works for me .
https://github.com/elix22/Urho3D/commit/e70b88b50d03f4c5039425337dc7413eaaa8d146

**Comment by billhollings** [comment]
@elix22 

Based on your code fix...you are referring to clearing an image (`vkCmdClearDepthStencilImage`)...and NOT an attachment (`vkCmdClearAttachments`)...correct?

I am not able to trigger a Metal assertion by clearing only the depth component of  `MTLPixelFormatDepth32Float_Stencil8` image.

What is the Metal assertion that you are encountering?

Do you have a small test app that demonstrates the issue? For example...you could try to modify `cube.c` in the MoltenVK Cube demo to trigger the assertion.

**Comment by elix22** [comment]
It is 100% reproducible with my code :

- git clone https://github.com/elix22/Urho3D.git
-  ./cmake_ios-metal.sh
-  open the generated Xcode project in "build-xcode-metal" folder
-  remove my fix from the code
-  build  and run sample **09_MultipleViewports**
- while the sample running press '**F**' on your keyboard


validateRenderPassDescriptor:634: failed assertion `When depth and stencil are used together, the texture bound to the depth and stencil render pass attachments must be the same depth and stencil texture.'

**Comment by elix22** [comment]
@billhollings were you able to reproduce this issue using my code ?

**Comment by billhollings** [comment]
@elix22 

Sorry for the delay in getting to this...and thanks for prompting me! I've been busy on other updates.

After commenting out your fix, I am not able to trigger the `validateRenderPassDescriptor`.

As an iOS app...there is no keyboard (I actually have an external iPad keyboard attached...but the app doesn't recognize its keypresses)...but there is an FXAA button on the screen. When I press that...there is no validation error...but it does result in a crash on `drawIndexedPrimitives:` several seconds later. This happens with or without you fix in place.

Can you provide me with additional steps to replicate what you were seeing, please?

I've attached screenshots of both the app UI (showing onscreen buttons) and the crash.

BTW...you'll notice on the crash screenshot that MoltenVK is logging what seems to be shader compilation happening on every frame. Is this intentional?

![screen shot 2019-02-28 at 5 58 23 pm](https://user-images.githubusercontent.com/356402/53604652-1294b180-3b83-11e9-8c2d-776cad2ece62.png)

![screen shot 2019-02-28 at 5 57 52 pm](https://user-images.githubusercontent.com/356402/53604791-7dde8380-3b83-11e9-9079-23831aee2962.jpg)

**Comment by billhollings** [comment]
Closing due to age. Please reopen and provide further info if this is still an issue.
