### ISSUE TITLE
Build system with external dependencies is weird

### ISSUE THREAD

**Issue by HansKristian-Work** [KhronosGroup/MoltenVK#507]
Yesterday I spent a few hours trying to figure out why I couldn't properly change some code in the SPIRV-Cross checkout and have it compile properly into MoltenVK. Apparently, if I modify a dependency and build using ./fetchDependencies, I first have to manually delete the Xcode DerivedData folder in $HOME/Library/Developer/Xcode/DerivedData, and then build MoltenVK for the changes to show up. Is this intentional? I don't know much about Xcode. Similar things seem to happen if I modify the ShaderConverter and then build MoltenVK. The changes are not always picked up properly.

**Comment by billhollings** [comment]
Hmmm...

Yes the separation of dependency libraries from MoltenVK is deliberate.

The reason is that some of the libraries take a long time to build (I'm looking at you `SPIRV-Tools`)...and for almost everyone who uses MoltenVK...they only need to be built once when they are originally fetched.

The dependency libraries are built in `MoltenVK/External/build` instead of `$HOME/Library/Developer/Xcode/DerivedData` so that Cleaning MoltenVK projects in Xcode...or blowing away the `$HOME/Library/Developer/Xcode/DerivedData` will not cause the dependencies to need to be rebuilt.

However...this approach does mean that those of us who work on the dependencies need to either purge `$HOME/Library/Developer/Xcode/DerivedData` manually...or run Clean on the project from Xcode.

I'll give it some more thought.

**Comment by billhollings** [comment]
BTW...just thinking about the upcoming SDK release...

In addition to CTS...are you running this PR against any real-world games that triggered this PR?

If so...and those tessellated games are running fine...and assuming this PR doesn't break anything existing...I'm good with including it in the upcoming release...and continuing to work on completing CTS conformance in the mainline evolution.

**Comment by billhollings** [comment]
Sorry...I just incorrectly posted a comment from another issue here by mistake. I've now deleted it.

**Comment by billhollings** [comment]
Fixed in PR #511.
