### ISSUE TITLE
Timestamp support in MoltenVK

### ISSUE THREAD

**Issue by petereichinger** [KhronosGroup/MoltenVK#520]
Is there any documentation about the values returned when using vk::CommandBuffer::writeTimestamp()?

On my Linux nvdia machine I get epoch timestamps but on moltenvk I get values that I cannot understand. 

For example: I have a command buffer with 6 timestamps and I took two timestamps with the system clock before and after. The system timestamps make sense but the 6 timestamps are all equal to each other and not in between the cpu timestamps.

**Comment by billhollings** [comment]
The queried timestamp value is the number of _ticks_ recorded since app startup. The duration between ticks is given by the `VkPhysicalDeviceLimits::timestampPeriod` value returned by `vkGetPhysicalDeviceProperties()`.

Unfortunately...on Metal the timestamps can only be as granular as a the completion of a Metal command buffer...which if `MVKConfiguration::prefillMetalCommandBuffers` is disabled (the default) will be once per Vulkan command buffer submission.
