### ISSUE TITLE
Linking to MoltenVK generates hundreds of weak symbol warnings

### ISSUE THREAD

**Issue by mbarriault** [KhronosGroup/MoltenVK#568]
This started a few weeks ago, but linking against MoltenVK.framework results in 130 warnings about weak symbols. They're all from symbols inside SPIRV-Cross, however as the source is compiled directly into libMoltenVK.a, this seems like a MoltenVK issue. This is after a full clean build of both MoltenVK, ExternalDependencies, and my own project. I've verified that the same headers are being used for all projects.

**Comment by mbarriault** [comment]
[Build log](https://github.com/KhronosGroup/MoltenVK/files/3065415/Build.Bearings-macOS_2019-04-10T19-26-48.txt)

**Comment by billhollings** [comment]
This typically happens when MoltenVK or your app is built in Debug mode and only for the macOS libraries. 

ExternalDependencies builds `libSPIRVCross.a` in Release mode...and there is a mismatch on public visibility when linking...even though Debug mode should have the same visibility settings as Release mode.

I haven't been able to resolve a fix for this yet. For now...when building the dylibs and the MoltenVK demo apps, we pass the `-w` build setting to suppress these spurious linker warnings. 

The dylib build script uses `-Xlinker -w` and the demo apps includes `-w` in the `OTHER_LDFLAGS` build setting.

**Comment by mbarriault** [comment]
Hm, okay. Strange that this didn't happen before, I've been using MoltenVK almost exclusively in Debug basically since it went open source. Is there any reason why a Debug target can't be added to ExternalDependencies? The project looks fairly straightforward.

**Comment by billhollings** [comment]
It's also strange that it is only SPIRV-Cross that is affected. SPIRV-Tools is not.

Originally...SPIRV-Cross was built right into `libMoltenVK.a`. Now SPIRV-Cross is first built into a separate `libSPIRVCross.a` library and then pre-linked into `libMoltenVK.a`. That's why it didn't happen before.

Yes...a Debug target could be added to ExternalDependiences...along with a debug switch to the `fetchDependencies` script. I'll look into adding that.

**Comment by mbarriault** [comment]
Resolved by #576.
