### ISSUE TITLE
vkCmdCopyBuffer requires copy sizes to be a multiple of 4 on macOS

### ISSUE THREAD

**Issue by mellinoe** [KhronosGroup/MoltenVK#62]
When calling [vkCmdCopyBuffer](https://www.khronos.org/registry/vulkan/specs/1.0/man/html/vkCmdCopyBuffer.html) under MoltenVK, each of the regions given needs to have a copy size that is a multiple of 4. Now, I understand that this is [a limitation of Metal on macOS](https://developer.apple.com/documentation/metal/mtlblitcommandencoder/1400767-copyfrombuffer?language=objc), but the Vulkan spec does not indicate there is any such limitation. Additionally, MoltenVK doesn't detect anything wrong and attempts to call the blit command encoder with unchanged parameters and triggers validation errors:

```
-[MTLDebugBlitCommandEncoder copyFromBuffer:sourceOffset:toBuffer:destinationOffset:size:]:898: failed assertion `size(30) must be a multiple of 4 bytes.'
```

I have a couple of questions:

* Is this considered "a bug" from MoltenVK's side? I understand that there may be things in the Vulkan API that cannot be emulated with full fidelity, although this seems to be one that can be worked around (even if it would be very roundabout and complicated).
* If not, is there a list of such discrepancies or instances where behavior is different from the spec?

**Comment by hideyhole** [comment]
Running into this too, and as far as I can tell, this seems to be a violation of the Vulkan spec.

**Comment by Tele42** [comment]
I'd like to point out that if this needs an always-on validation to catch this at runtime, it is against the design goals of both vulkan and metal.

In the worse case scenario, I think it would be best to create a vulkan layer that catches quirks that MoltenVK can't handle and the application dev should be allowed to enable individual quirk workarounds as necessary so overhead could be kept as low as possible.

**Comment by billhollings** [comment]
For the most part, buffer alignments will be at least 4 bytes (as per Vulkan limits like `minUniformBufferOffsetAlignment` and `minStorageBufferOffsetAlignment`). Therefore...on macOS, we could align the `VkBufferCopy::size`value to the next 4-byte boundary, under the assumption that, because of those alignments, such a copy would NOT stomp over the first few bytes of whatever data followed the region in the buffer. This alignment would not be needed for iOS.

If that is a valid assumption, we could skip generating a runtime error. If not...perhaps we could generate and log the error, but still continue processing.

@mellinoe 

The Vulkan Portability Initiative that Khronos announced along with the open-sourcing of MoltenVK is working to define a portable subset for Vulkan that would define how to build a Vulkan app that will work across all platforms...both compliant native Vulkan implementations, and non-native implementations such as MoltenVK. This is an example of the kind of thing that will be included in that.

@Tele42 

Notwithstanding possible runtime alignment that I mention above...the intention is NOT to catch such validations at runtime...as per the Vulkan and Metal design you indicate. As part of the Vulkan Portability initiative, LunarG is planning to implement portability validation layers that can be engaged to help ensure that a Vulkan app is designed to be portable.

**Comment by mellinoe** [comment]
@billhollings I think there's a misunderstanding here. This is about `vkCmdCopyBuffer`, which copies data between two buffers (which already have been bound to memory, etc.). The copy regions specified are from the beginnings of those buffers. The Vulkan spec doesn't place any limitations on how large or small those regions are, as long as they are non-zero-sized and fit within the actual size of the buffer. This implies that a buffer offset of 1, and a copy size of 1, are legal and permitted.

The alignment requirements you are referring to only apply to buffers being bound into a descriptor, at least as far as I can tell. They don't place any restrictions on `vkCmdCopyBuffer`.

I guess the real question we're trying to get at: is MoltenVK intended to be a conforming Vulkan implementation, or does it only implement the portable subset? If it's the former, then MoltenVK needs to internally handle these discrepancies between API's, and do so unconditionally. If it's the latter (which I think you are alluding to), then I think that warrants a larger discussion, because I personally am not sure what consequences it has.

**Comment by billhollings** [comment]
@mellinoe 

I don't think there is a misunderstanding. I'm talking about `vkCmdCopyBuffer` too.

Alignment becomes a factor here if we are able to recognize that even in a copy that involves single-byte boundaries...almost ALL such copies will involve data that is aligned to a larger boundary (eg- a single float meets the 4-byte boundary requirement).

That means that in almost all practical cases...data _following_ the destination target would almost certainly NOT be overwritten incorrectly if we round up to the next four-byte boundary and allow Metal to copy into the 2 or 3 bytes following the destination target.

Perhaps we could output a warning error so that developers are alerted to the imperfect scenario...but still allow the copying anyway for those that don't care.

My comments above were to open those design questions up for discussion. And I invite others to contribute to that design discussion. **Is it reasonable to allow MoltenVK to expand the copy region to a 4-byte boundary?**

To clarify overall design intent...MoltenVK is dependent on Metal. So full _Vulkan_ conformance is not possible at this point (or maybe ever). The purpose of _Vulkan Portability Initiative_ at _Khronos_ is to recognize this...and figure out what level of compatibility IS possible on each platform (and OS version)...and to provide documentation, runtime feedback, and tools to help developers manage their portability concerns.

WRT what compliance CAN be possible...some will be direct...and other compliance may be synthetic within MoltenVK at some level. At each point...design decisions will need to be addressed. And this forum is a good place to discuss those.

I'll add some text to the `README.md` to make this concept more generalized and recognized.

**Comment by karl-lunarg** [comment]
I think that the issue here is the case where you might want to copy a non-mult-of-4 number of bytes from one buffer to another when NOT at the end of the buffers.  That is, `srcOffset` and `dstOffset` might both be 0, but `size` is 5, in a `VkBufferCopy` structure.   The buffers are both much bigger than 5 bytes, perhaps hundreds of bytes.  Clearly, you don't want to round the size up to 8 here because the 3 bytes at offsets 5, 6, and 7 in the destination will get written unintentionally.

Does Metal have the notion of a "write mask"?  In this example, you could write the first 4 bytes normally but set a write mask so that only the first byte of the next 4-byte write actually makes it to the destination.  It wouldn't be that hard or performance-killing to handle the more general cases which probably include masked writes at both ends of the copy if not aligned.  A write mask seems essential on a system that has a minimum transfer granularity of 4 bytes.

**Comment by mellinoe** [comment]
@billhollings Thanks for the discussion -- I really appreciate it. Like I said, I'm still trying to get a feel for the library and what its goals and non-goals are, so any clarification is helping.

> Alignment becomes a factor here if we are able to recognize that even in a copy that involves single-byte boundaries...almost ALL such copies will involve data that is aligned to a larger boundary (eg- a single float meets the 4-byte boundary requirement).

> That means that in almost all practical cases...

I won't argue that copies like this are the common case, or that they are even optimal. But there are some simple scenarios where these things can crop up quite easily, and they are permitted by the Vulkan spec. For example, a 16-bit index buffer is likely to have a size which is not a multiple of 4, unless you explicitly pad out the size. Any odd number of indices will give you some size that's not divisible by 4. This is the case that I'm running into in one of my library's sample projects, for example. Now, I could certainly bump up the size of my buffer manually (actually, this is what my library does when running on Metal), but it's not required when running on Vulkan, and the spec doesn't have a problem with it. If I'm trying to update the first half of my indices (with a copy command), then padding out to 4-byte boundaries is going to cause data to be overwritten. I'll admit that this is not what's happening in my case, but I think it's a legitimate example. 

> Is it reasonable to allow MoltenVK to expand the copy region to a 4-byte boundary?

I would argue "no", it is not reasonable. I think such a decision should be explicit by the developer, and a validation error needs to be raised if the rule is violated. I think it is also very important that any usage errors be validated in a Vulkan layer, not by Metal itself. This is important because I don't want to require macOS to ensure that I'm using MoltenVK correctly. Realistically, most of my development will be done on Windows or Linux, so ideally I could catch any usage errors on any platform. If the D3D12->Vulkan translation layer also becomes a reality, then I definitely don't want to be cross-checking 3 different validation rulesets on multiple platforms to ensure that I'm using things correctly.

Lastly, I would just like to step back and re-address the title issue. Although it's true that [MTLBLitCommandEncoder.copyFromBuffer](https://developer.apple.com/documentation/metal/mtlblitcommandencoder/1400767-copyfrombuffer?language=objc) has a restriction on copy sizes/alignment, there is an alternative that would maintain full fidelity of Vulkan's vkCmdCopyBuffer. MoltenVK could instead dispatch a compute shader with the source and destination buffers bound, and do a byte-by-byte copy. I've validated that this is feasible in my own graphics library, although I haven't integrated it yet (I have a hackier solution for non-aligned buffer copies at the moment which works ok for me).

```C++
#include <metal_stdlib>
using namespace metal;

struct CopyInfo
{
    uint32_t SrcOffset;
    uint32_t DstOffset;
    uint32_t CopySize;
};

kernel void copy_bytes(
    device uint8_t* src [[ buffer(0) ]],
    device uint8_t* dst [[ buffer(1) ]],
    constant CopyInfo& info [[ buffer(2) ]])
{
    for (uint32_t i = 0; i < info.CopySize; i++)
    {
        dst[i + info.DstOffset] = src[i + info.SrcOffset];
    }
}
```

This is not an optimal compute shader by any means, just a proof of concept. From looking at the code for clearing framebuffer attachments (#61), it seems MoltenVK already issues synthetic draw calls in places that don't necessarily imply a draw call (like clearing textures). So I think using a compute shader in this circumstance would be in line with that approach. This compute shader could just be used as a "slow path" -- only needed when the copy regions are misaligned. For regular, aligned buffer copies, MTLBlitCommandEncoder's buffer copy can be used.

**Comment by billhollings** [comment]
@mellinoe 

Thanks for the rebuttal and examples. I appreciate you highlighting common use cases that need to be accommodated.

Your idea of using a compute shader (when forced to) makes sense. As you indicate, MoltenVK already uses this approach with certain synthetic draw calls. And Vulkan only permits `vkCmdCopyBuffer()` outside a renderpass...so flipping to a `MTLComputeCommandEncoder ` won't interrupt an existing `MTLRenderCommandEncoder`.

And thanks for the shader reference implementation!

**Comment by mellinoe** [comment]
I've submitted a full integration of the above solution: #99 .

**Comment by darksylinc** [comment]
Hi everyone! I'm the maintainer of Ogre 2.x branch, and we hit this exact problem (which btw will disappear in macOS Catalina).

I couldn't help notice your version of the compute shader is... too inefficient.
It leaves a single thread to handle the entire copy.

Considering AMD GCN takes 4 clocks to execute a single instruction, just moving around memory would take 8 cycles per byte (one for load, another for store) without counting overhead (loop instructions, wait instructions, etc).

I guess it's ok because most unaligned copies wouldn't be bigger than a few KBs in size. But some pathological cases could end up performing very slow.

Nonetheless there are faster ways to do it (aka low hanging fruits). The following compute shader will take advantage of all threads:

```
#include <metal_stdlib>
using namespace metal;

struct Params
{
	uint32_t dstOffset;
	uint32_t srcOffset;
	uint32_t sizeBytes;
};

kernel void ogre_gpu_memcpy
(
	device uint8_t* dst			[[ buffer(0) ]],
	device uint8_t* src			[[ buffer(1) ]],
	constant Params &p			[[ buffer(2) ]],
	uint3 gl_GlobalInvocationID	[[thread_position_in_grid]]
)
{
	uint32_t srcOffsetStart	= p.srcOffset + gl_GlobalInvocationID.x * 64u;
	uint32_t dstOffsetStart	= p.dstOffset + gl_GlobalInvocationID.x * 64u;
	uint32_t numBytesToCopy	= min( 64u, p.sizeBytes - gl_GlobalInvocationID.x * 64u );
	for( uint32_t i=0u; i<numBytesToCopy; ++i )
		dst[i + dstOffsetStart] = src[i + srcOffsetStart];
}
```

Basically what it does is to have each thread copy 64 bytes, then issue many threads.
The last thread in the last threadgroup will copy fewer than 64 bytes.

macOS GPUs can issue up to 1024 threads per workgroup. I don't know how many workgroups can be issued, but if we use OpenGL's minimum limits (65535) then with this function we can copy up to 4GB = 64 bytes per thread * 1024 threads per workgroup * 65535 workgroup.
The original kernel used uint32_t so 4GB was already the limit anyway.

To dispatch the threads use:

```
MTLSize threadsPerThreadgroup   = MTLSizeMake( 1024u, 1u, 1u );
MTLSize threadgroupsPerGrid     = MTLSizeMake( 1u, 1u, 1u );

const size_t threadsRequired	= alignToNextMultiple( sizeBytes, 64u ) / 64u;
threadsPerThreadgroup.width	= std::min<NSUInteger>( threadsRequired, 1024u );
threadgroupsPerGrid.width	= alignToNextMultiple( threadsRequired, threadsPerThreadgroup.width ) / threadsPerThreadgroup.width );

[computeEncoder dispatchThreadgroups:threadgroupsPerGrid
               threadsPerThreadgroup:threadsPerThreadgroup];
```

I don't know if this is THE best of performing a copy via compute (bank conflicts are hard to think of because by definition we're copying data unaligned data), but it should certainly be better than leaving 1 thread to perform the entire copy.

[I've pushed and tested my implementation]( https://bitbucket.org/sinbad/ogre/commits/150a48c2790d664688e12d6908df9d1224a2afea) in our Ogre repository, branch 2.2 if anyone wants to see it.

Cheers
