### ISSUE TITLE
Providing workgroup size when passing custom MSL

### ISSUE THREAD

**Issue by BearishSun** [KhronosGroup/MoltenVK#632]
When compiling a compute shader from MSL source code (using the magic number), I'm not seeing an option for providing the workgroup size (i.e. numbers of threads per threadgroup). Looking at the code this seems to be deduced from `SPIR-V Cross` when SPIR-V -> MSL conversion is made, but when passing MSL source I cannot find a way to assign it (it is assumed to be 1, 1, 1).

Is there a way to assign the workgroup size while also using MSL source code?

**Comment by BearishSun** [comment]
(I wouldn't mind something like `vkSetThreadgroupSizeMVK` that can be called on the shader module post-compilation).

**Comment by billhollings** [comment]
> (I wouldn't mind something like `vkSetThreadgroupSizeMVK` that can be called on the shader module post-compilation).

Certainly a possibility.

What is your goal in submitting MSL directly? I ask because if the reason is to avoid the cost of runtime conversion from SPIR-V to MSL...another approach might be to make use of standard Vulkan pipeline caching within your app.

MoltenVK's implementation of pipeline cache serialization outputs/inputs converted shader MSL, plus entry-point info such as workgroup size, so that future access to a cached pipeline will avoid the SPIRV-MSL conversion.

**Comment by BearishSun** [comment]
Our high level design currently prevents pipeline caching, without major changes we are not yet ready for. So we are only relying on individual shader code caching.

Regardless, since cached pipelines are device dependent (at least as far as Vulkan spec is concerned, not sure about MoltenVK), having pre-compiled MSL or Metal intermediate code is still beneficial as it avoids that initial compile step, which can be considerable as we use uber shaders that can amount to thousands of variations.
