### ISSUE TITLE
MVK_DEBUG not dumping shader source

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/MoltenVK#649]
I'm trying to get more information on a shader compile failure on the version of MoltenVK to ship with the 1.1.108 SDK (which seems like it's fixed on latest but I want to be sure), and the docs suggested that I should be able to set the environment variable `MVK_DEBUG=1` to get shader source dumps like I do on debug builds, but nothing changed in the output when I ran with that.

Side-note, I went down a rabbit hole for quite a while trying to use `VK_MVK_moltenvk` to set the `debugMode` configuration parameter manually until I found #492 that said the extension is not expected to work when using the loader. Since using the loader is the correct way for most applications to use vulkan this should really be made very clear in the documentation that it won't work before people try to use it.

**Comment by billhollings** [comment]
Thanks. Very strange that the environment var is not working. I'll have a look.

Thanks for the suggestion about the documentation. I agree we should clarify that.

**Comment by billhollings** [comment]
@baldurk 

It looks like `vulkansdk/macOS/lib/libMoltenVK.dylib` in the 1.1.108 SDK was built with logging disabled.

You can retrieve and build the [version of MoltenVK used in the SDK](https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.0.35), and then replace `vulkansdk/macOS/lib/libMoltenVK.dylib` with a symlink to it.

I'll discuss MoltenVK logging with the Vulkan SDK team.

PR #650 adds a documentation about not using opaque objects between layers.

**Comment by eintw1ck** [comment]
For more context `MVK_CONFIG_TRACE_VULKAN_CALLS=2` does work but `MVK_CONFIG_LOG_LEVEL=2` doesn't. I think the expected behaviour should be `MVK_CONFIG_LOG_LEVEL=01 by default but able to change it at runtime?

**Comment by billhollings** [comment]
@eintw1ck Unfortunately...`MVK_CONFIG_LOG_LEVEL` will have no effect since MoltenVK in the 1.1.108 SDK was built with logging turned completely off, using a separate flag.

LunarG has made a [fix](https://github.com/KhronosGroup/Vulkan-Tools/pull/217) to their MoltenVK build process, to do exactly what you suggest. Future versions of MoltenVK in the SDK will run with `MVK_CONFIG_LOG_LEVEL` set to log errors only...and an app dev can override that at runtime by setting the `MVK_CONFIG_LOG_LEVEL` environment variable.
