### ISSUE TITLE
Contribution Guidelines

### ISSUE THREAD

**Issue by mellinoe** [KhronosGroup/MoltenVK#69]
I'm interested in fixing some of the issues I encountered (separate issues filed), but I don't see any information regarding external contributions. A few questions:

* Are contributions accepted? I assume there is some sort of CLA process that likely needs to be followed, but I'm not sure. I think the answer to the above is "yes", but I guess I'm more interested in the specifics of the process.
* Are there any validation tests I can run? Obviously I'm interested in fixing the code so that my rendering library works on top of it, but that won't give very broad coverage.
* What's the best way to get questions answered about the implementation and/or the best approach for a fix? Discussing things in individual issues works fine for me, but I'm not sure if there are other channels that are more convenient.
* Are there more technical docs available anywhere? The docs in here are mostly end-user docs rather than for devs working on MoltenVK itself.

Thanks for all of the work on this library, I'm looking forward to using it!

**Comment by oscarbg** [comment]
Perhaps @billhollings original creator of MoltenVK has some info to share..

**Comment by billhollings** [comment]
@mellinoe 

- Thanks for your interest in contributing. We definitely would welcome your contributions. That was one of the main drivers behind making MoltenVK open-source.

- Since we're all just starting out down this road together with MoltenVK, we don't have a formal contribution process in place yet other than the standard GitHub Pull Request mechanism. For now, I'll review each PR...and we can branch out from that to include other reviewers if I become a bottleneck.

- Regarding questions and discussions...for now...I suggest you post issues for discussion. If it looks like we need a FAQ or other forum...we can expand into that at some point.

- Regarding unit tests, there are none as part of MoltenVK itself. Khronos does have an incredibly comprehensive [CTS test suite](https://github.com/KhronosGroup/VK-GL-CTS) for validating Vulkan drivers. It makes sense that we piggy-back on that. MoltenVK has NOT been tested against that suite yet...but doing so should definitely be a goal.

- The `README.md` and `MoltenVK_Runtime_UserGuide.md` docs are the primary starting point. There are no "architecture" documents yet. I'll be interested in suggestions there. I would definitely encourage MoltenVK contributors to make liberal use of code comments to outline design decisions and explanations as we move forward.

**Comment by mellinoe** [comment]
@billhollings Thank you for the answers. I think that is a good starting point. For now, I'll close this, and we can work through more in individual issues as we go.
