### ISSUE TITLE
Scissor rect needs to be clamped to viewport width

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/MoltenVK#70]
We use static scissor and dynamic viewport configuration when creating the pipeline state:

	VkRect2D scissor = {};
	scissor.offset.x = 0;
	scissor.offset.y = 0;
	scissor.extent.width = 16384;
	scissor.extent.height = 16384;

	VkPipelineViewportStateCreateInfo viewportState = {};
    viewportState.sType = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO;
    viewportState.viewportCount = 1;
    viewportState.pViewports = nullptr; // dynamic
    viewportState.scissorCount = 1;
    viewportState.pScissors = &scissor;

In MoltenVK, with this setup we get a Metal validation error when trying to use this with a correctly sized viewport:

> -[MTLDebugRenderCommandEncoder setScissorRect:]:2565: failed assertion `(rect.x(0) + rect.width(16384))(16384) must be <= render pass width(256)'

I believe what should happen is that the scissor rect from the pipeline state should be clamped to viewport dimensions.

**Comment by danginsburg** [comment]
Possibly related to #16.  I believe @billhollings added something to clamp this in debug builds of MoltenVK.

**Comment by mellinoe** [comment]
I'm a bit concerned by that linked issue (#16). Is Metal validation expected to be run in order to ensure "proper" usage of MoltenVK? I could be wrong, but I (and I think others) are operating under the assumption that conforming Vulkan code (e.g. follows the rules and restrictions of the Vulkan spec), should run without modification under MoltenVK. This would imply that viewport clamping (or anything else necessary for proper Metal usage), would be done unconditionally, in all build configurations.

It's definitely possible that I'm missing some context. I'm new to the project so I'm still trying to get a general feel for how things are supposed to work.

**Comment by danginsburg** [comment]
I am inclined to agree with @mellinoe that the clamping should not be conditional on debug.  Even if it seems to not be a problem on any Metal implementations we tried, having it run with clean Metal validation all the time is desirable.  We do want it to be the case that a valid Vulkan app will produce valid Metal calls, although there will be some corner cases that are tricky to handle (i.e. viewport/scissor of size 0,0 as discussed in #16).  The goal is that the Khronos portability API will add additional constraints that validation will check to make sure of this.  That's a big goal of that initiative (so you can rely on just passing validation to make sure your app is valid - we're just not there yet).

**Comment by billhollings** [comment]
Hmmm...this is a devtime/runtime optimizing question.

Both the Vulkan and Metal approach is to bypass validation checks within the driver at runtime.

Metal's validation code is the equivalent of running validation layers under Vulkan. It's something that is deliberately requested on top of the basic driver...when performance is NOT a concern. 

Similarly with MoltenVK debug mode. Currently...the design expectation is that during development, a developer would turn on Vulkan validation layers, Metal validation, and MoltenVK debug mode...but then turn all three off at release runtime.

The reason this particular test is made only in Debug mode within MoltenVK...was because its ONLY purpose is to suppress a Metal validation check that would NOT normally be run on a release build. Leaving the scissor overlap does NOT cause a runtime issue within the basic Metal driver...which successfully ignores the overlap.

So...adding this MoltenVK outside of Debug mode would cause MoltenVK to always run code whose ONLY purpose would be to suppress Metal validation code that would NOT normally be running in a production runtime.

The question then is whether we want to incur possible runtime performance hits running MoltenVK code that performs no function at driver runtime. This seems counter to the Vulkan/Metal principal of the basic driver NOT wasting time on validation unless it is deliberately requested.

BTW...even with a Release build of MoltenVK...it is still possible to turn on Debug mode via the runtime API using `vkGet/SetMoltenVKDeviceConfigurationMVK()`. The expectation here is to allow an app to have a runtime ability to flip to Debug mode (perhaps via a UI toggle).

Happy to hear further thoughts.

**Comment by zeux** [comment]
@billhollings My thoughts on the matter: I don't think MoltenVK should be in a position to judge Metal validation errors as critical or non-critical. If there's an error then it might be malfunctioning on some iOS release or macOS vendor; to know that this is not a problem today you need to test several iOS versions and drivers on 3 macOS versions for 3 different vendors. Additionally, if MoltenVK based apps run into a driver bug and it's reported to Apple, the first thing they will probably say is "your app hits a validation error".

There might be specific cases when the overhead is so large that working around the issue makes MoltenVK impractical from the performance standpoint, but this should be the judgement and it should be explicitly documented (e.g. "Release MoltenVK runtime can trigger Metal validation error such and such; you can enable the workaround for this using this API but beware that the cost of doing it can be up to 20% slower rendering").

I think it's perfectly fair for MoltenVK to misbehave when it's used in ways that don't conform to Vulkan spec, even if it's not validated by the current layers; however, I don't believe this issue falls into that category.

**Comment by danginsburg** [comment]
> I think it's perfectly fair for MoltenVK to misbehave when it's used in ways that don't conform to Vulkan spec, even if it's not validated by the current layers; however, I don't believe this issue falls into that category.

I agree with @zeux

**Comment by billhollings** [comment]
@zeux  & @danginsburg

I just want to be sure I understand the recommendation.

Based on the feedback here...the design choice seem to be one of:

1. MoltenVK always clamps scissor rect.

2. MoltenVK always validates and reports error on values that would trigger Metal validation were it enabled. 

3. MoltenVK validates and reports only in Debug mode (current behaviour).

If I'm reading the discussion correctly...it sounds like (1) is the preferred approach...correct?

**Comment by zeux** [comment]
@billhollings Yes, correct. FWIW looking at the Vulkan spec, this is actually explicitly allowed by it:

> It is legal for offset.x + extent.width or offset.y + extent.height to exceed the dimensions of the framebuffer - the scissor test still applies as defined above. Rasterization does not produce fragments outside of the framebuffer, so such fragments never have the scissor test performed on them.

**Comment by billhollings** [comment]
@zeux 

Yeah...and I suspect Metal behaves the same way under the covers...making Metal validation really more of a friendly reminder than a real indication of potential disaster...hence the restriction of the clamping to Debug only.

But you and @danginsburg have made good points about MoltenVK making assumptions...and so we will convert the clamping to "always on".

**Comment by billhollings** [comment]
Fixed in PR #118. Please retest.
