### ISSUE TITLE
On iOS, using dylib per instructions will result in App Store rejection

### ISSUE THREAD

**Issue by SpuriousWarning** [KhronosGroup/MoltenVK#739]
If you try to upload an application that is dynamically linking MoltenVK per the instructions in the [MoltenVK Runtime User Guide: Installing MoltenVK in Your Vulkan Application](https://github.com/KhronosGroup/MoltenVK/blob/master/Docs/MoltenVK_Runtime_UserGuide.md#install) to the App Store, you will receive this message:
> Invalid Bundle Structure - - The binary file 'YOURAPP.app/libMoltenVK.dylib' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure.

**Comment by billhollings** [comment]
As a stop-gap...PR #744 includes documentation in `MoltenVK_Runtime_UserGuide.md` clarifying that static libraries are the recommended mechanism for linking to **MoltenVK** in _iOS_.

If anyone has success in bundling `libMoltenVK.dylib` into an iOS app, getting it into the iOS App Store, and can provide bundling info...we can include those instructions in the `MoltenVK_Runtime_UserGuide.md` as well.

**Comment by danginsburg** [comment]
You can keep MoltenVK as a dynamic library as long as it is embedded in your application bundle as a framework.  We have passed iOS App Store approval this way.

**Comment by billhollings** [comment]
> embedded in your application bundle as a framework

Thanks @danginsburg. 

Can you clarify what that means in practice? Is it simply a matter of copying `libMoltenVK.dylib` into the `My.app/Frameworks` folder? Or is there some other black magic required?

And did you need to make any adjustments to the default `@rpath/libMoltenVK.dylib` embedded in `libMoltenVK.dylib` when it is built?

**Comment by jurganson** [comment]
@danginsburg @billhollings I am currently sitting with the exact same issue - trying to upload an app to the App Store which should contain the libMoltenVK.dylib however I am running into App Store rejections because of it. 

I have tried to embed the dynamic library inside a Framework but to no avail as either it ends up in a /Frameworks folder which is considered an umbrella framework which is not allowed in the App Store either or it is rejected because of the placement of the .dylib file.

Is this the right approach (to try to embed it inside a framework and then import that framework in the app) or does the .dylib file need to be directly inside the MyApp.app/Frameworks/ folder where all the other frameworks? If so, is there a good way of making sure it ends up there?

**Comment by jurganson** [comment]
@billhollings I finally made the App Store pass using MoltenVK as a dynamic library. The final solution for me was following the instruction here: https://stackoverflow.com/a/62962641

Although it seemed a little bit like black magic, it was the thing that finally worked for me.

My final thoughts are that **if you can**, _use MoltenVK as a static library_ if you plan on developing iOS.

**Comment by billhollings** [comment]
@jurganson Thanks for looping back here and providing the solution that worked for you, so others can benefit from it.
