### ISSUE TITLE
Support Vulkan 1.1

### ISSUE THREAD

**Issue by cdavis5e** [KhronosGroup/MoltenVK#822]
As of version 1.5.2, DXVK now requires a Vulkan 1.1 implementation. This means that until MoltenVK supports 1.1, we won't be able to use it with DXVK. I expect that the number of applications requiring Vulkan 1.1 is going to increase in the future as 1.0 ICDs become rarer. Much has been done to move towards this, but there's still much to be done.

Remaining 1.1 tasks:
- [x] `VK_KHR_external_fence` and `VK_KHR_external_fence_capabilities`
- [x] `VK_KHR_external_memory` and `VK_KHR_external_memory_capabilities`
- [x] `VK_KHR_external_semaphore` and `VK_KHR_external_semaphore_capabilities`
- [x] [`VK_KHR_multiview`](/KhronosGroup/MoltenVK/issues/347) - SPIRV-Cross work is already done
- [x] `VK_KHR_sampler_ycbcr_conversion` - SPIRV-Cross work is already done
- [ ] Feature struct for `VK_KHR_shader_draw_parameters`
- [x] Subgroup operations - SPIRV-Cross work is already done
- [ ] Protected memory - Metal exposes no API for this, but we still need to fill in the feature struct, if only to say we don't support it
- [ ] `vkEnumerateInstanceVersion()`

**Comment by oscarbg** [comment]
just reposting here from dxvk issue:
also slightly related noticed recently two Vulkan projects have recently updated needing/benefiting also from Vulkan 1.1 support:
*VKD3D DXIL branch:
https://www.winehq.org/pipermail/wine-devel/2020-January/158470.html
Vulkan 1.1 for wave ops:
"Vulkan 1.1 is enabled if active, because subgroup operations requires it. SM 6.0 support is only activated if subgroup operations are sufficiently supported and DXIL is enabled.
There are other features required for SM 6.0 such as 16-bit arithmetic and storage, but that is left for later."
*VkBasalt (since 1.3) "Vulkan 1.1 is now required"
https://github.com/DadSchoorse/vkBasalt/releases/tag/v0.3.0

**Comment by 741g** [comment]
This is awesome news! Android/Fuchsia Emulator on macOS has heretofore used the Vulkan 1.0 or Swiftshader Vulkan 1.1 on macOS, but looks like we can use 1.1 there now which lets us ship with something supporting Vulkan 1.1 on all 3 platforms (macos/windows/linux) :)
