### ISSUE TITLE
A question for OpenGL ES2

### ISSUE THREAD

**Issue by azoreseuropa** [KhronosGroup/MoltenVK#853]
My macOS laptop was 2014 and Intel Iris 1536 MB. Where do I put OpenGL ES 2 files in ?

**Comment by billhollings** [comment]
@azoreseuropa 

MoltenVK is a Vulkan implementation. Can you clarify what you mean by OpenGL ES 2 files? 

If you are interested in OpenGL ES 2, are you thinking of [MoltenGL](https://moltengl.com/moltengl/), instead of MoltenVK? If so, please submit your questions for MoltenGL through the [Contact form](https://moltengl.com/contact/) on that website, or via email to support@moltengl.com.

**Comment by azoreseuropa** [comment]
I just realised that MoltenGl and MoltenVK is demo. You have to pay for it to be full, is that correct ? And I am talking bout OpenGL ES 2. There are two files in zip. Where should I put them ? Unless those are also a demo ?

**Comment by billhollings** [comment]
MoltenVK is an implementation of Vulkan, is open-source, and is the product connected to this repository and issue list.

MoltenGL is an implementation of OpenGL ES 2, is a licensed product, and is not connected to this repository. Please submit questions about MoltenGL to the contact info I provided above.

**Comment by azoreseuropa** [comment]
Thank you. I shall closed it now.
