### ISSUE TITLE
LICENSE is missing year / copyright owner

### ISSUE THREAD

**Issue by starbucksDave** [KhronosGroup/MoltenVK#858]
The current [LICENSE](https://github.com/KhronosGroup/MoltenVK/blob/master/LICENSE) file contains:
```
Copyright [yyyy] [name of copyright owner]
```
Could this be be filled in ?

Thanks!

**Comment by billhollings** [comment]
I think you're referring to the `APPENDIX` in that file. That section defines a _template_ of what needs to be placed in each source file to claim the Apache license for that source file. 

The content defined in that `APPENDIX` appears in each MoltenVK source file, with the appropriate  copyright date and owners substituted. But the template itself in the `APPENDIX` should not be modified, otherwise it would lose its use as a template.

I'll close this now. Please reopen if it requires further discussion.
