### ISSUE TITLE
Support for depth-only texture arrays.

### ISSUE THREAD

**Issue by prideout** [KhronosGroup/MoltenVK#866]
I work on [Filament](https://github.com/google/filament)'s Vulkan backend using a mac and I love MoltenVK.

However we hit a brick wall since Filament relies on depth texture arrays for many of its framebuffer effects (e.g. SSAO).  Could this limitation be easily lifted?  I'm referring to this feature:

https://github.com/KhronosGroup/MoltenVK/blob/1a25de55002fe0e2a834bda6233b245c2e3c230c/MoltenVK/MoltenVK/GPUObjects/MVKImage.mm#L673

**Comment by cdavis5e** [comment]
In Vulkan, like in D3D10+, there is no real distinction between a 2D image and a 2D array image. They both use `VK_IMAGE_TYPE_2D`. In Metal, they are distinct, though you can create texture views between both types. I guess that error message is confusing because, even though it's talking about Metal's capabilities, it's doing so with Vulkan's terms. Depth textures work equally well for 2D array images in Metal as they do with 2D images. You should be able to create 2D array images with a depth/stencil format in MoltenVK.

**Comment by prideout** [comment]
Thanks!  Still a little confused.  If Vulkan has no real distinction between a 2D image and a 2D array image, then what is the purpose of `VK_IMAGE_VIEW_TYPE_2D_ARRAY` and `VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT`?

**Comment by cdavis5e** [comment]
In shaders, there is still a distinction between a 2D image (`image2D` and `sampler2D` in GLSL) and a 2D array image (`image2DArray` and `sampler2DArray`). Views are what you pass to shaders via descriptor sets, so views need to keep track of the distinction between non-arrayed and arrayed views.

`VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT` is used when creating 3D images. It allows you to create a 2D array image view out of a 3D image. The most common reason you'd need to do that is to render to a subset of a 3D image. Indeed, this is the only use case MoltenVK supports for that bit, since Metal doesn't support creating 2D array texture views from 3D textures, but it does allow limiting which portions of a 3D texture are rendered to.

**Comment by prideout** [comment]
@cdavis5e thanks for your help!  You set me straight.  Closing.

**Comment by prideout** [comment]
I might need to re-open this actually. 

> there is no real distinction between a 2D image and a 2D array image. They both use VK_IMAGE_TYPE_2D

If this is true, then why does the  the Vulkan spec state the following?

```
 If imageType is VK_IMAGE_TYPE_2D, extent.depth must be 1
```

https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkImageCreateInfo-imageType-00957

**Comment by prideout** [comment]
Woops, never mind -- I probably need to set `arrayLayers` rather than `depth`.  Sorry for the spam.
