### ISSUE TITLE
Undefined symbol `___isPlatformVersionAtLeast` while linking with libmoltenvk.a

### ISSUE THREAD

**Issue by MaikKlein** [KhronosGroup/MoltenVK#913]
Since version 1.0.42 we are getting the symbol `___isPlatformVersionAtLeast` in `libmoltenvk.a`, which is failing our builds.

>   = note: Undefined symbols for architecture x86_64:
>             "___isPlatformVersionAtLeast", referenced from:
>                 MVKPresentableSwapchainImage::presentCAMetalDrawable(id<MTLCommandBuffer>, bool, unsigned int, unsigned long long) in libash_molten-f9a8f3466dcc62c4.rlib(libMoltenVK.a-x86_64-master.o)
>           ld: symbol(s) not found for architecture x86_64
>           clang: error: linker command failed with exit code 1 (use -v to see invocation)

For context we have a project that statically links moltenvk https://github.com/EmbarkStudios/ash-molten

The error is reproducible on multiple local machines, and it also fails on the CI https://github.com/EmbarkStudios/ash-molten/runs/757461072#step:5:13

```
OSX 10.15.5
Xcode 11.5
```

Do you have any idea where `___isPlatformVersionAtLeast` is coming from and how to resolve it? 
I have read somewhere that it is supposed to be defined in `compiler-rt`  and re-exported in `libSystem`, but at least that is not the case for me.

**Comment by billhollings** [comment]
@MaikKlein 

I tried downloading and building your environment...and I too see the error shown above.

I'm [fairly certain](https://forums.developer.apple.com/thread/123003) this has to do with the use of `@available()` in`MVKPresentableSwapchainImage::presentCAMetalDrawable()`.

It does not happen in other uses of MoltenVK `libMoltenVK.a`, specifically in the MoltenVK Demos.

In order to work on a fix, I tried to figure out how to re-jig your build environment (`build.rs`) so that it would attempt to link to a different `libMoltenVK.a` file via a symbolic link...so that I can plug in a locally-built version rather than always fetching `v1.0.43` from the public repo...but I couldn't figure out your build environment and build sequence well enough to make that happen.

Can you provide me with an alternate `build.rs` that would allow me to identify the location of a `libMoltenVK.a` outside of `ash-molten` (maybe via a sym-link inside `ash-molten`) so that I can work on figuring out what's going on, and fixing this, please? 

Or just tell me how I can run the full build once and then substitute in a different `libMoltenVK.a`, and attempt the final linking stage to your environment, over and over, with a new `libMoltenVK.a` each time.

Thanks.

**Comment by MaikKlein** [comment]
Thanks for looking into it.

> In order to work on a fix, I tried to figure out how to re-jig your build environment (build.rs) so that it would attempt to link to a different libMoltenVK.a file via a symbolic link...so that I can plug in a locally-built version rather than always fetching v1.0.43 from the public repo...but I couldn't figure out your build environment and build sequence well enough to make that happen.

What you can do is this

```bash
RUSTFLAGS="-L YOUR_SEARCH_PATH" cargo build --features external
```
ash-molten will skip building moltenvk and just look for it in your search path if you use `--features external`.

**Comment by billhollings** [comment]
PR #914 includes a fix for this. Please retest and close this issue if it works.

If you need MoltenVK to cut a release so that your automated script can pull from the repo, let me know, and we can do that in the next couple of days.

**Comment by MaikKlein** [comment]
@billhollings Thank you, this fixed it for us.

> If you need MoltenVK to cut a release so that your automated script can pull from the repo, let me know, and we can do that in the next couple of days.

We are currently on 1.0.41, I think we can just skip 42/43 and wait for 1.0.44, we don't have any immediate issues with it.

Thanks again for the timely fix
