### ISSUE TITLE
VkPhysicalDeviceSubgroupProperties

### ISSUE THREAD

**Issue by Lichtso** [KhronosGroup/MoltenVK#918]
Based on https://github.com/KhronosGroup/SPIRV-Cross/pull/982 I would like to add the following struct to VkPhysicalDeviceProperties2:
```
case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBGROUP_PROPERTIES: {
	auto* physicalDeviceSubgroupProps = (VkPhysicalDeviceSubgroupProperties*)next;
    physicalDeviceSubgroupProps->supportedStages =
        VK_SHADER_STAGE_COMPUTE_BIT |
        VK_SHADER_STAGE_ALL_GRAPHICS;
    physicalDeviceSubgroupProps->supportedOperations =
        VK_SUBGROUP_FEATURE_BASIC_BIT |
        // VK_SUBGROUP_FEATURE_VOTE_BIT |
        VK_SUBGROUP_FEATURE_ARITHMETIC_BIT |
        VK_SUBGROUP_FEATURE_BALLOT_BIT |
        VK_SUBGROUP_FEATURE_SHUFFLE_BIT |
        VK_SUBGROUP_FEATURE_SHUFFLE_RELATIVE_BIT |
        VK_SUBGROUP_FEATURE_CLUSTERED_BIT |
        VK_SUBGROUP_FEATURE_QUAD_BIT;
        // VK_SUBGROUP_FEATURE_PARTITIONED_BIT_NV;
    physicalDeviceSubgroupProps->quadOperationsInAllStages = true;
	break;
}
```
@cdavis5e I understand there are some Metal specific limitations here, so are these bit-fields correct(ish)?

### subgroupSize
Of course, the biggest problem is the `subgroupSize` field.

One way would be to compile a minimal compute shader and ask it for its `MTLComputePipelineState.threadExecutionWidth`. However, I don't understand how this is shader code dependent and why it is not part of the physical device in Metal.

The other way is the hacky one:
According to http://gpuinfo.org all subgroupSizes (of GPUs supported by Metal) are 32 for Intel and Nvidia and 64 for AMD. So it could simply be done like this:
`physicalDeviceSubgroupProps->subgroupSize = (strstr(getName(), "AMD") || strstr(getName(), "Radeon")) ? 64 : 32;`

Edit: We can also just check the vendor ID instead of a string compare:
`_metalFeatures.subgroupSize = (_pProperties->vendorID == 0x1002) ? 64 : 32;`

**Comment by cdavis5e** [comment]
> @cdavis5e I understand there are some Metal specific limitations here, so are these bit-fields correct(ish)?

We can't support this in vertex or tessellation evaluation shaders, and we currently don't support geometry shaders at all, so `supportedStages` should be `COMPUTE | TESSELLATION_CONTROL | FRAGMENT`.

Why is `VK_SUBGROUP_FEATURE_VOTE_BIT` disabled? All three of the vote ops (`All`, `Any`, `AllEqual`) are implemented and should work on macOS. It's `CLUSTERED` that can't be supported properly.

We can only support all these features on macOS 10.14. We can't support it at all on prior versions. According to the spec, if any queues support `COMPUTE`, then `VK_SHADER_STAGE_COMPUTE_BIT` will be set in `supportedStages`. But curiously, it doesn't use a normative "**must**" here. (Have you noticed how some words in the spec are bolded and purple? The sentences with those words are [*normative*](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/chap1.html#introduction-normative-terminology).) This could probably use a clarification from the working group. If it's required, and I think it was meant to be, then macOS 10.13 and earlier will be stuck at Vulkan 1.0.

> Of course, the biggest problem is the `subgroupSize` field.
> 
> One way would be to compile a minimal compute shader and ask it for its `MTLComputePipelineState.threadExecutionWidth`. However, I don't understand how this is shader code dependent and why it is not part of the physical device in Metal.

So when the shader is compiled down to low-level device code, it uses a certain number of registers. If it uses too many, the driver will reduce the number of threads in the SIMD-group, presumably because some of the GPU's resources are being used to support the extra registers. This is actually a problem for Vulkan on other OSes as well. For this reason, the [`VK_EXT_subgroup_size_control`](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/chap47.html#VK_EXT_subgroup_size_control) was proposed to support implementations--like Metal--that vary the subgroup size based on things like register usage.

We have two options here, until `VK_EXT_subgroup_size_control` is implemented, and even then when the `VK_PIPELINE_SHADER_STAGE_CREATE_ALLOW_VARYING_SUBGROUP_SIZE_BIT_EXT` isn't specified. Either, we can say the subgroup size is the maximum allowed, and the missing threads will appear to be inactive; or, we can reduce the subgroup size with some math on the subgroup variables. The latter behavior is required when the `VK_PIPELINE_SHADER_STAGE_CREATE_REQUIRE_FULL_SUBGROUPS_BIT_EXT` is set. This will need some work on SPIRV-Cross.

**Comment by Lichtso** [comment]
Thanks for your detailed response!

I updated the flags and will use the `vendorID` to determine `subgroupSize` for now.
We can then later add the `VK_EXT_subgroup_size_control` extension after we reached Vulkan 1.1
