### ISSUE TITLE
Using multiple swap chain kills performance on macOS

### ISSUE THREAD

**Issue by dolphineye** [KhronosGroup/MoltenVK#929]
Hi guys,

Today, I tried to use multiple swap chains for multiple windows rendering.

When I create my second window with my secondary swap chain, my performance drops by 50%. Note that I use GLFW as my window management system and I use MoltenVK 1.2.135 (LunarG). I also use triple buffering (3 swap chain images).

The Xcode profiler results indicate that my main thread is spending 32 msec waiting for the next drawables (2 x 16 msec to be accurate).

I'm pretty sure I'm missing something, so I've decided to post an issue in case someone would have a clue.

Thanks for helping!

**Comment by dolphineye** [comment]
Hey, just bumping this issue with additional information. We ran a test with our app in a Linux environment  with Vulkan, and everything's fine. So, it's likely to be something related to MoltenVK.

What information would you need for a more detailed report to address that issue?

Thanks

**Comment by FunMiles** [comment]
Could this be the same issue as in https://github.com/KhronosGroup/MoltenVK/issues/581 ? I have had a drop from 60fps to 30fps in general when having more than one window ever since I've started playing with more than one window. 
I've observed stranger result still more recently but haven't had time to look into them.

**Comment by billhollings** [comment]
They might indeed be related...but #581 discusses a wide range of situations.

> I have had a drop from 60fps to 30fps in general when having more than one window ever since I've started playing with more than one window.

Per this thread, are you using more than one swapchain to do this?

**Comment by dolphineye** [comment]
Hi guys,

Thanks for helping 👍 Just back from vacation, so back to business now :)

> With your triple buffering, are you using 3 images per swapchain? So 6 swapchain images total?

Yes, I'm using 3 swap chain images for each window. Hence N x 3 swap chain images depending on how many of them are open.

> Do you have a sample app that you can upload to the cloud so we can investigate?

Working on it. I'll get back to you as soon as I have it for you.

**Comment by dolphineye** [comment]
I've just stumbled on this post: https://developer.apple.com/forums/thread/651571

**Comment by billhollings** [comment]
> I've just stumbled on this post, if that helps: https://developer.apple.com/forums/thread/651571

Interesting. Thanks for highlighting that.

Hmmm...we can certainly experiment with using `-[MTLDrawable present]` and `-[MTLDrawable presentAtTime:]` instead of `-[MTLCommandBuffer presentDrawable:]` and `-[MTLCommandBuffer presentDrawable:atTime:]`.

But I must admit, I find the answer in that thread curious. It almost appears to be answering a different question than was asked. The drawable stalls are caused at the `-[CAMetalLayer nextDrawable]` retrieval end, not at the presentation end.

Not to mention that the [documentation](https://developer.apple.com/documentation/metal/mtlcommandbuffer/1443029-presentdrawable?language=occ) for `-[MTLCommandBuffer presentDrawable:]` is:

>This is a convenience method that calls the drawable’s present method after the command queue schedules the command buffer for execution.

which is basically what we'd be doing in making this change.

Essentially, it's hard to see how using separate queues for presenting, or avoiding `-[MTLCommandBuffer presentDrawable:]` will help with the fundamental limit of 3 concurrent swapchain drawables. I suppose it's possible that there is poor internal design, causing the command buffer or queue to retain the drawable well after the buffer and queue are finished, but that would be very odd indeed.

Nevertheless, I'll add it to the dev list. If you get a chance to experiment with this in the meantime, please report results here.

**Comment by dolphineye** [comment]
> Essentially, it's hard to see how using separate queues for presenting, or avoiding `-[MTLCommandBuffer presentDrawable:]` will help with the fundamental limit of 3 concurrent swapchain drawables. I suppose it's possible that there is poor internal design, causing the command buffer or queue to retain the drawable well after the buffer and queue are finished, but that would be very odd indeed.

I would be surprised as well that something like that wasn't spotted already by anyone else. In my case, as far as I can remember, we were stalling on `waitForNextDrawable`, not at presentation time as you mentioned. But well, who knows...

> Nevertheless, I'll add it to the dev list. If you get a chance to experiment with this in the meantime, please report results here.

Thanks. I was sidetracked on something else this afternoon, but I will try to get a sample app ready for you by the end of the week :)

**Comment by billhollings** [comment]
@dolphineye This may have been fixed in PR #1090. Can you retest and verify, please? If it has been fixed, please close this issue.

**Comment by dolphineye** [comment]
I confirm this has fixed the multi-window issue (double checked).

But it seems that we now have a crash:

```
[CAMetalLayerDrawable texture] should not be called after already presenting this drawable. Get a nextDrawable instead.
[CAMetalLayerDrawable present] should not be called after already presenting this drawable. Get a nextDrawable instead.
```

Do you also reproduce or is it likely it's an issue in our implementation ?

**Comment by dolphineye** [comment]
Not sure it's going to help, but here's the crash callstack:

![image](https://user-images.githubusercontent.com/31071122/95181814-08f21780-07c4-11eb-9c16-e3d13c97a81f.png)

**Comment by dolphineye** [comment]
For some reasons, it seems this fixed the issue:

```diff
-       [mtlCmdBuff addScheduledHandler: ^(id<MTLCommandBuffer> mcb) {
-               presentCAMetalDrawable(presentTimingInfo);
-       }];
+       presentCAMetalDrawable(presentTimingInfo);
```

Alternatively, this solution seems to be working as well:

```diff
-       [mtlCmdBuff addScheduledHandler: ^(id<MTLCommandBuffer> mcb) {
-               presentCAMetalDrawable(presentTimingInfo);
-       }];
-
        // Ensure this image is not destroyed while awaiting MTLCommandBuffer completion
        retain();
        [mtlCmdBuff addCompletedHandler: ^(id<MTLCommandBuffer> mcb) {
+               presentCAMetalDrawable(presentTimingInfo);
                makeAvailable();
                release();
        }];
```

**Comment by billhollings** [comment]
@dolphineye 

Thanks for your detailed debugging and reporting. Looks like there is a race condition on retrieving the drawable.

PR #1092 should fix this. Can you pull the latest and retest, please?

**Comment by dolphineye** [comment]
Just tested this morning, that's all good so far 👍. Thanks for addressing this issue, much appreciated!

Closing issue!
