### ISSUE TITLE
vkGetPhysicalDeviceFormatProperties incorrectly reports `*FILTER_LINEAR_BIT` in tiling features

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/MoltenVK#945]
`vkGetPhysicalDeviceFormatProperties` on iOS (macOS is okay) incorrectly reports that the linear tiling features of a VK_FORMAT_R8G8B8A8_UNORM image support `VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT`. This leads to my application trying to create a mipmapped image in this format with fails with the following message on the console (1st line is from MVK, 2nd is from my application):

```
[mvk-error] VK_ERROR_FEATURE_NOT_PRESENT: vkCreateImage() : If tiling is VK_IMAGE_TILING_LINEAR, mipLevels must be 1.
Fatal error in ktxLoadVkTexture*: VkResult is "-8" in /Users/mark/Projects/khronos/github/KTX-Software/lib/vkloader.c at line 1037
```

On macOS MVK correctly does not include `VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT` in the reported linear tiling features for this format so my app does not try to create the image..

This is new since the MoltenVK that was in Vulkan SDK 1.1.85.0. I'm currently using Vulkan SDK 1.2.141.2.

**Comment by cdavis5e** [comment]
> `vkGetPhysicalDeviceFormatProperties` on iOS (macOS is okay) incorrectly reports that the linear tiling features of a VK_FORMAT_R8G8B8A8_UNORM image support `VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT`.

That's correct. This is because you can use a sampler with a linear filter with such an image.

> This leads to my application trying to create a mipmapped image in this format with fails

Why are you checking for that format feature instead of testing the maximum mip levels returned by `vkGetPhysicalDeviceImageFormatProperties()`? If you make this call:
```c
VkImageFormatProperties props;
vkGetPhysicalDeviceImageFormatProperties(physDev, VK_FORMAT_R8G8B8A8_UNORM, imaageType, VK_IMAGE_TILING_LINEAR, flags, &props);
```
then `props.maxMipLevels` should be 1, meaning you can't create a mipmapped linear image.

> On macOS MVK correctly does not include `VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT` in the reported linear tiling features for this format so my app does not try to create the image..

Wait, why are we not setting that on macOS? The only format features we shouldn't be setting for linear tiling are the attachment features. That's the only restriction on usage I know of for macOS GPUs.

**Comment by MarkCallow** [comment]
> That's correct. This is because you can use a sampler with a linear filter with such an image.

The Vulkan spec says

```
VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT specifies that if VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT
is also set, an image view can be used with a sampler that has either of magFilter or minFilter set to VK_FILTER_LINEAR, or
mipmapMode set to VK_SAMPLER_MIPMAP_MODE_LINEAR.
```

So you have to have this feature *and* `props.maxMipLevels > 1? And 1.1.85.0 was broken in not advertising this feature?

**Comment by cdavis5e** [comment]
> The Vulkan spec says
> 
> ```
> VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT specifies that if VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT
> is also set, an image view can be used with a sampler that has either of magFilter or minFilter set to VK_FILTER_LINEAR, or
> mipmapMode set to VK_SAMPLER_MIPMAP_MODE_LINEAR.
> ```

Right, but `mipmapMode` only applies if the image in question has more than one mip level. I haven't found any normative language forbidding the use of a sampler with a `LINEAR` mipmap mode with a non-mipmapped image.

> So you have to have this feature _and_ `props.maxMipLevels > 1?

No. If you want to create a mipmapped image, you only need `props.maxMipLevels > 1`. The `SAMPLED_IMAGE_FILTER_LINEAR` feature only affects which filters you're allowed to use. I'd imagine that mipmapping is still useful even without trilinear filtering, since derivative calculations in the fragment shader still affect which LoD the sampling functions use. It just won't be a blend of two mip levels.

> And 1.1.85.0 was broken in not advertising this feature?

Yes, and it's still broken on macOS.

**Comment by billhollings** [comment]
>>`vkGetPhysicalDeviceFormatProperties` on iOS (macOS is okay) incorrectly reports that the linear tiling features of a `VK_FORMAT_R8G8B8A8_UNORM` image support `VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT`.

>>macOS MVK correctly does not include `VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT` in the reported linear tiling features for this format

>Wait, why are we not setting that on macOS? The only format features we shouldn't be setting for linear tiling are the attachment features. That's the only restriction on usage I know of for macOS GPUs.

@MarkCallow 

When I run `vkGetPhysicalDeviceFormatProperties(VK_FORMAT_R8G8B8A8_UNORM)` on MoltenVK macOS, I get the following results:

        optimal = 0xDD83
         linear = 0xD403
    (difference = 0x0980)

So from what I see...

    VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT = 0x00001000,

...is enabled in both optimal and linear. And as @cdavis5e expected, relative to optimal, the only items disabled for linear are the three attachment-dependent format features:

    VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT = 0x00000080,
    VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT = 0x00000100,
    VK_FORMAT_FEATURE_BLIT_DST_BIT = 0x00000800,

You can verify this using the `cube.c` demo in MoltenVK (and Vulkan-Tools) which calls `vkGetPhysicalDeviceFormatProperties ` on `VK_FORMAT_R8G8B8A8_UNORM`, which is how I tested it.

If you calling this function through the SDK, could a validation layer be interfering somehow?

**Comment by MarkCallow** [comment]
I see the same feature sets you report on macOS. On iOS both optimal and linear are 0xdd83.

The reason my app bailed on macOS and attempted to run on iOS is because it is also looking for `VK_FORMAT_FEATURE_BLIT_DST_BIT` which is not present on macOS. If it is correct for this bit to be set for linear on iOS, you can close this issue.

Thank you for the education. I am changing my app to check `props.maxMipLevels` from `vkGetPhysicalDeviceImageFormatProperties`  whenever it is attempting to load a mip mapped texture.

**Comment by billhollings** [comment]
>VK_FORMAT_FEATURE_BLIT_DST_BIT which is not present on macOS. If it is correct for this bit to be set for linear on iOS

Linear attachments are supported on iOS, but not on macOS, which is why the three flags I indicate above `VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT`, `VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT`,
`VK_FORMAT_FEATURE_BLIT_DST_BIT`) are elided on macOS.

The removal of `VK_FORMAT_FEATURE_BLIT_DST_BIT` as part of this restriction might seem strange. The reason it is removed is because Vulkan BLIT operations permit scaling regions, whereas Metal does not. To accommodate this feature, MoltenVK performs scaled BLIT operations by rendering, which requires the destination image to be a renderable attachment. Because of this need, formats that cannot be rendered to cannot be a BLIT destination.
