### ISSUE TITLE
Support VK_get_physical_device_properties2

### ISSUE THREAD

**Issue by gverm** [KhronosGroup/MoltenVK#949]
It was promoted to core in 1.1. [Wine's vulkan_1 tests](https://source.winehq.org/git/wine.git/blob/HEAD:/dlls/vulkan-1/tests/vulkan.c#l161) crash without it.

**Comment by cdavis5e** [comment]
We already support that extension. I know this because I implemented it myself, because DXVK and vkd3d needed it.

**Comment by gverm** [comment]
@cdavis5e I might be missing something, but I can only find vkGetPhysicalDeviceProperties2KHR and not vkGetPhysicalDeviceProperties2.

**Comment by billhollings** [comment]
>I can only find `vkGetPhysicalDeviceProperties2KHR` and not `vkGetPhysicalDeviceProperties2`.

MoltenVK currently supports Vulkan 1.0, plus extensions. So from a spec perspective, `vkGetPhysicalDeviceProperties2KHR` is appropriate at present.

Outstanding requirements for us to move to Vulkan 1.1 are being tracked in #822.

Are you needing to make use of 1.1 function names, because the Wine implementation is assuming Vulkan 1.1? Is this something Wine can bypass with some internal redirection headers?

If not, we'd need to support that mapping internally to MoltenVK, which is possible, and is eventually required as we move to 1.1, but for the time-being you'd be calling 1.1 functions on a 1.0 implementation.

**Comment by gverm** [comment]
> Outstanding requirements for us to move to Vulkan 1.1 are being tracked in #822.

Understood. I thought opening a separate issue would be best, but if everything is being tracked in #822, that's definitely fine.

> Are you needing to make use of 1.1 function names, because the Wine implementation is assuming Vulkan 1.1? Is this something Wine can bypass with some internal redirection headers?
> 
> If not, we'd need to support that mapping internally to MoltenVK, which is possible, and is eventually required as we move to 1.1, but for the time-being you'd be calling 1.1 function names on a 1.0 implementation.

The Wine tests should definitely handle it not being available. I'll open a Wine bug for this.
